const {test}=require('node:test');const assert=require('node:assert/strict');
const {ShutdownCoordinator}=require('./shutdown.cjs');
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};};
const menu={page:'menu',experienceDirty:false,ruleEditing:false,modal:false,transitioning:false};
function harness(){let state={status:'ready',installPlan:{mode:'now',generation:1},generation:1},active=false;const events=[],listeners=[];const updates={read:()=>({...state}),onChange:fn=>listeners.push(fn),cancelInstallPlan:()=>{state.installPlan=null;listeners.forEach(fn=>fn());},verifyReady:async()=>events.push('verify'),handoffInstall:()=>events.push('native')};const privacy={setIdle:()=>{},restartSuspended:v=>events.push(v?'suspend':'resume'),read:()=>({warning:null}),persistenceBarrier:async()=>events.push('disk')};const c=new ShutdownCoordinator({updates,privacy,canPrepare:()=>!active,sendPrepare:r=>events.push(r),cleanup:async()=>events.push('cleanup'),backup:async()=>events.push('backup'),onGate:v=>events.push(v?'gate':'ungate')});return {c,events,updates,privacy,state,setActive:v=>active=v};}
test('nonce waits for clean menu, independently blocks active port, and consumes one native permission',async()=>{
 const h=harness();h.c.report({...menu,page:'settings',experienceDirty:true});assert.equal(h.c.pending,null);h.setActive(true);h.c.report(menu);assert.equal(h.c.pending,null);h.setActive(false);h.c.report(menu);const request=h.c.pending;await assert.rejects(h.c.reply({...request,nonce:'old',ready:true}),/RESTART_STALE/);await h.c.reply({...request,ready:true});assert.equal(h.events.filter(x=>x==='native').length,1);assert.equal(h.c.handedOff,true);await assert.rejects(h.c.reply({...request,ready:true}),/RESTART_STALE/);assert.deepEqual(h.events.filter(x=>['disk','backup','cleanup','verify','native'].includes(x)),['disk','backup','cleanup','verify','native']);h.c.close();
});
test('stop during disk barrier or failed stop persistence invalidates the old ACK and never installs',async()=>{
 for(const writeFailed of [false,true]){const h=harness(),barrier=deferred();h.privacy.persistenceBarrier=()=>barrier.promise;h.c.report(menu);const request=h.c.pending,work=h.c.reply({...request,ready:true});if(writeFailed)h.privacy.read=()=>({warning:'STOPPED_NOT_SAVED_RETRY_NEXT_START_MAY_RESTORE'});else h.c.invalidate(true);barrier.resolve();await assert.rejects(work,/RESTART_CANCELLED/);assert.ok(!h.events.includes('native'));assert.equal(h.c.handedOff,false);h.c.close();}
});
test('renderer reload/dirty transition invalidates a pending nonce; cancel after native has no effect',async()=>{
 const h=harness();h.c.report(menu);const old=h.c.pending;h.c.report({...menu,modal:true});await assert.rejects(h.c.reply({...old,ready:true}),/RESTART_STALE/);h.c.report(menu);await h.c.reply({...h.c.pending,ready:true});h.c.invalidate(true);assert.equal(h.c.handedOff,true);assert.equal(h.events.filter(x=>x==='native').length,1);h.c.close();
});
