import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { DesktopView, Manual, Option, Profile, ProfileInput, Reply, Scene, Settings } from './types';
import { groups, orderedOptions, shortcutEntry } from './interaction';
import { ddText, pollViews } from './view-loop';
const api=window.desktop;
const groupName={attack:'攻击',defense:'防御',skill:'技能'};
const avatarName={leaf:'叶子',sun:'太阳',moon:'月亮',star:'星星'};
const errors:Record<string,string>={PACKAGE_INCOMPLETE:'游戏文件不完整，请重新取得完整测试包。',INVALID_PROFILE:'昵称须为 1—20 个字，不能包含控制字符；请选择内置头像。',INVALID_INPUT:'输入格式无效，请检查后重试。',SAVE_FAILED:'保存失败，请检查本机目录权限后重试。输入和旧档案已保留。',PROFILE_BUSY:'正在保存，请稍后重试。',PROFILE_DAMAGED:'本机档案损坏，原文件已保留。',PROFILE_UNREADABLE:'暂时无法读取档案，请检查目录权限后重试。',UNAVAILABLE_MOVE:'这张牌暂不可用，请查看原因。',STALE_VIEW:'场景已更新，请重新选择。',ALREADY_SUBMITTED:'已经提交，请等待揭晓。',MATCH_INTERRUPTED:'本场中断，可重新开始。',GET_VIEW_FAILED:'读取对局失败，请重新读取或退出。',REQUEST_CONFLICT:'本拍已提交另一张牌，请重新读取。',SESSION_CLOSED:'本场已结束，请返回菜单重新开始。'};
const reasons:Record<string,string>={INSUFFICIENT_DD:'DD 不足',INSUFFICIENT_LIGHTNING:'雷电不足',INSUFFICIENT_CHARGE:'充能不足',INSUFFICIENT_BOMBS:'成熟层不足',ALREADY_USED:'本局已用',NO_COPY_RECORD:'没有复制记录',NO_REWARD:'奖励未就绪',FORCED_RECOVERY:'正在休整',NOT_ACTIVE:'已不在场'};
const message=(code:string)=>errors[code]||`操作未完成（${code}），请重试。`;
function Avatar({id='leaf'}:{id?:string}) {return <span className={`avatar ${id}`} aria-label={avatarName[id as keyof typeof avatarName]||'占位头像'}><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M10 35 Q4 12 24 8 Q45 12 38 35 Q24 44 10 35Z"/><path d={id==='sun'?'M18 6 L17 1 M32 7 L35 2 M41 17 L47 15':id==='leaf'?'M24 9 Q13 0 12 9 Q13 15 24 9':id==='moon'?'M32 9 Q22 19 36 23':'M22 2 L24 7 L30 7 L26 11'}/><path d="M15 24 L17 24 M30 24 L32 24 M20 31 Q24 34 28 30"/></svg></span>;}
function Modal({title,children,onClose,closeDisabled=false}:{title:string;children:React.ReactNode;onClose:()=>void;closeDisabled?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose();}} aria-label={title}><header><h2>{title}</h2><button disabled={closeDisabled} onClick={onClose} aria-label="关闭弹窗">×</button></header>{children}</dialog>;
}
function Identity({nickname,avatar,onName,onAvatar,disabled=false}:{nickname:string;avatar:string;onName:(s:string)=>void;onAvatar:(s:string)=>void;disabled?:boolean}) {
 return <fieldset disabled={disabled}><label>你的昵称<input aria-label="昵称" autoComplete="off" value={nickname} onChange={e=>onName(e.target.value)}/><small>1—20 个字，仅保存在这台电脑。</small></label><span className="label">选一个纸上头像</span><div className="avatars">{Object.entries(avatarName).map(([id,name])=><button key={id} type="button" aria-label={`头像：${name}`} aria-pressed={avatar===id} onClick={()=>onAvatar(id)}><Avatar id={id}/></button>)}</div></fieldset>;
}
function App() {
 const [profile,setProfile]=useState<Profile|null>(null),[page,setPage]=useState('loading'),[error,setError]=useState('');
 const [nickname,setNickname]=useState(''),[avatar,setAvatar]=useState('leaf'),[saving,setSaving]=useState(false),[damaged,setDamaged]=useState(false);
 const [view,setView]=useState<DesktopView|null>(null),[manual,setManual]=useState<Manual|null>(null),[scene,setScene]=useState<Scene>('initial');
 const [modal,setModal]=useState(''),[detail,setDetail]=useState<Option|null>(null),[rule,setRule]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('all');
 const [settings,setSettings]=useState<Settings>({music:60,effects:70,fullscreen:false}),[settingsTab,setSettingsTab]=useState('声音'),[returnPage,setReturnPage]=useState('menu');
 const submitLock=useRef(false), generation=useRef(0), readSlot=useRef(false), sceneChangePending=useRef(false);
 const [readError,setReadError]=useState(false),[readAttempt,setReadAttempt]=useState(0),[busy,setBusy]=useState(false),[resourcePlayer,setResourcePlayer]=useState('');
 const take=<T,>(r:Reply<T>):T=>{if(!r.ok)throw new Error(r.error);return r.data;};
 const run=async(action:()=>Promise<void>)=>{setError('');try{await action();}catch(e){setError(message((e as Error).message));}};
 const load=async()=>{await run(async()=>{try{const p=take(await api.profile.read());setProfile(p);setPage(p?'menu':'profile');setDamaged(false);}catch(e){setDamaged((e as Error).message==='PROFILE_DAMAGED');setPage('profile');throw e;}});};
 useEffect(()=>{void load();void api.manual().then(r=>{if(r.ok)setManual(r.data);});},[]);
 const selected=view?.options.find(o=>o.entry_id===view.selected_entry_id);
 const editable=!readError && !busy && !!view && ['selecting','error'].includes(view.phase) && !view.submitted && view.options.length>0;
 const choose=(id:string)=>{if(editable)setView(v=>v?{...v,selected_entry_id:id}:v);};
 const submit=async()=>{
   if(!view||!selected||!editable||submitLock.current||sceneChangePending.current)return;
   submitLock.current=true;setBusy(true);const token=++generation.current;setError('');
   try {const next=take(await api.port.submit(view.view_id,selected.entry_id));if(token===generation.current)setView(next);}
   catch(e){if(token===generation.current){setError(message((e as Error).message));if((e as Error).message==='MATCH_INTERRUPTED')setReadError(true);}}
   finally {submitLock.current=false;if(token===generation.current){setBusy(false);setReadAttempt(n=>n+1);}}
 };
 useEffect(()=>{
  const onKey=(e:KeyboardEvent)=>{
   const t=e.target as HTMLElement;
   if(e.repeat||e.isComposing||e.altKey||e.ctrlKey||e.metaKey||modal||detail||rule||resourcePlayer||page!=='table'||!editable||t.closest('input,textarea,select,[contenteditable="true"],dialog'))return;
   const entry=shortcutEntry(view!.options,e.key,false);
   if(entry){e.preventDefault();choose(entry);}else if(e.key==='Enter'){e.preventDefault();void submit();}
  };
  window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);
 });
 useEffect(()=>{
  if(page!=='table'||!view||view.phase==='result'||readError)return;
  const token=generation.current, match=view.match_id, source=view.source;
  return pollViews(()=>api.port.getView(),readSlot,next=>{
    if(token!==generation.current||next.match_id!==match||next.source!==source||submitLock.current)return;
    setView(previous=>next.phase==='selecting'&&previous?.view_id===next.view_id
      ? {...next,selected_entry_id:previous.selected_entry_id} : next);
    if(next.phase==='result')setPage('result');
  },code=>{if(token===generation.current){setReadError(true);setError(message(code));}});
 },[page,view?.match_id,view?.source,readError,readAttempt]);
 const navigate=(action:()=>void)=>{if(!sceneChangePending.current)action();};
 const changeScene=async(action:()=>Promise<DesktopView>,nextPage:string)=>{
  if(sceneChangePending.current||busy)return;sceneChangePending.current=true;const token=++generation.current;setBusy(true);setError('');setReadError(false);
  try {const next=await action();if(token===generation.current){setView(next);setPage(nextPage);setModal('');}}
  catch(e){if(token===generation.current){setError(message((e as Error).message));setReadError(true);}}
  finally {sceneChangePending.current=false;if(token===generation.current)setBusy(false);}
 };
 const start=()=>profile?changeScene(async()=>take(await api.port.startSolo(profile.local_id)),'table'):Promise.resolve();
 const preview=(s:Scene)=>{if(sceneChangePending.current)return;setScene(s);return changeScene(async()=>take(await api.preview(s)),['winner','draw'].includes(s)?'result':'table');};
 const leave=async()=>{
  if(sceneChangePending.current)return;
  ++generation.current;setBusy(false);setView(null);setPage('menu');setModal('');setReadError(false);
  await run(async()=>{take(await api.port.leave());});
 };
 const openSettings=()=>{if(!profile||sceneChangePending.current)return;setNickname(profile.nickname);setAvatar(profile.avatar_id);setSettings({...profile.settings});setReturnPage(page);setError('');setPage('settings');};
 const dirty=profile&&(nickname!==profile.nickname||avatar!==profile.avatar_id||JSON.stringify(settings)!==JSON.stringify(profile.settings));
 const closeSettings=()=>{if(saving||sceneChangePending.current)return;if(dirty)setModal('settings-close');else{setPage(returnPage);setError('');}};
 const save=async(recover=false)=>{
  if(saving)return;setSaving(true);
  await run(async()=>{const input:ProfileInput={nickname,avatar_id:avatar};const p=take(await (page==='settings'?api.settings.apply({...input,settings}):recover?api.profile.recover({...input,confirmed:true}):api.profile.create(input)));setProfile(p);setDamaged(false);setModal('');setPage(page==='settings'?returnPage:'menu');});
  setSaving(false);
 };
 const live=view?.source==='live';
 const resourceDetail=view?.participants.find(p=>p.player_id===resourcePlayer);
 const self=view?.participants.find(p=>p.player_id===view.self_id);
 const ordered=view?orderedOptions(view.options):[];
 const hotkeys=new Map(ordered.filter(o=>o.available).slice(0,10).map((o,i)=>[o.entry_id,String((i+1)%10)]));
 const detailEntry=detail&&manual?.entries.find(o=>o.entry_id===detail.entry_id);
 const pageTitle:Record<string,string>={profile:'初次见面',menu:'课间开始了',prepare:'单人准备',table:view?.options.length?(view.participants.length===2?'双人牌桌':'六人开发预览'):'观战开发预览',result:'整场结果',settings:'本机设置',manual:'经典手册',loading:'正在打开'};
 return <div className="app">
  <header className="topbar"><button className="brand" disabled={sceneChangePending.current} onClick={()=>navigate(()=>page==='settings'?closeSettings():page==='table'?setModal('leave'):(setPage(profile?'menu':'profile'),setError('')))}>叠叠<span>DeiDei</span></button><span className="page-title">{pageTitle[page]}</span><strong className="demo-label">{view?(live?'本地实算 · 临时随机对手':'演示数据 · 固定脚本'):'本地单人 · 经典规则 1.0.1'}</strong>{profile&&<button disabled={page==='settings'||busy} onClick={()=>navigate(()=>setModal('preview'))}>开发预览</button>}</header>
  <div className="size-warning">当前内容区较小，建议调大窗口或降低系统显示缩放；牌区保持可读字号。</div>
  {error&&<div className="error" role="alert">{error}{readError&&<span><button onClick={()=>{setError('');setReadError(false);setReadAttempt(n=>n+1);}}>重新读取对局</button><button disabled={sceneChangePending.current} onClick={()=>void leave()}>退出本场</button></span>}<button onClick={()=>setError('')} aria-label="收起错误">×</button></div>}
  {page==='loading'&&<main className="center"><p>正在读取本机档案…</p></main>}
  {page==='profile'&&<main className="center"><section className="paper profile"><span className="eyebrow">P01 · 本机档案</span><h1>先写下你的名字。</h1><p>不用注册。下一次打开，还会在这里遇见你。</p><Identity nickname={nickname} avatar={avatar} onName={setNickname} onAvatar={setAvatar} disabled={saving}/>{damaged?<><p>原档案不会自动覆盖。确认重建前，会先备份原文件。</p><button className="primary" disabled={saving} onClick={()=>setModal('recover')}>备份原文件并重建档案</button></>:<button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'保存中…':'保存，进入课间 →'}</button>}<button onClick={()=>void load()}>重新读取</button></section></main>}
  {page==='menu'&&profile&&<main className="menu-layout"><section><span className="eyebrow">纸上的课间 · R02</span><h1>攒一拍，<br/>再出招。</h1><p>那些课间的招式，<br/>一起慢慢做成能玩的游戏。</p><div className="signed"><Avatar id={profile.avatar_id}/><span>{profile.nickname}<small>本机档案已保存</small></span></div></section><nav className="menu-actions"><button className="primary" disabled={sceneChangePending.current} onClick={()=>navigate(()=>{setPage('prepare');setError('');})}>单人对局 <span>→</span></button><button disabled={sceneChangePending.current} onClick={()=>navigate(()=>setModal('online'))}>好友联机 <small>尚未加入</small></button><button disabled={sceneChangePending.current} onClick={()=>navigate(()=>{setReturnPage('menu');setPage('manual');})}>经典规则手册</button><button disabled={sceneChangePending.current} onClick={openSettings}>设置</button><button onClick={()=>void api.quit()}>退出</button><p>和临时随机对手练习。<br/>本机实算，练习不限时。</p></nav></main>}
  {page==='prepare'&&profile&&<main className="center"><section className="paper prepare"><span className="eyebrow">P03 · 单人准备</span><h1>先来一场，练练手。</h1><div className="versus"><div><Avatar id={profile.avatar_id}/><h3>{profile.nickname}</h3><small>本人</small></div><b>×</b><div><Avatar id="sun"/><h3>临时随机对手</h3><small>从合法招式中等概率选择</small></div></div><p>经典规则 1.0.1 · 练习不限时</p><p>对手在你出牌前选好本拍招式；双方一起由经典规则结算。</p><button className="primary" disabled={busy} onClick={()=>void start()}>{busy?'正在开场…':'开始单人对局'}</button><button disabled={sceneChangePending.current} onClick={()=>navigate(()=>setPage('menu'))}>返回</button></section></main>}
  {page==='table'&&view&&<main className="table" data-phase={view.phase}>
   <div className={`public-area ${view.participants.length===2?'duo':''}`}><div className="opponents">{view.participants.filter(p=>p.player_id!==view.self_id).map(p=><div key={p.player_id} className={`seat ${p.alive?'':'out'}`}><Avatar id={p.avatar_id}/><span>{p.nickname}<small>{p.alive?view.phase==='revealed'?'已揭晓':p.submission_state==='submitted'?'已提交 · 招式未揭晓':'思考中':'已淘汰 · 本场不再加入'}</small><button className="seat-resources" title={`DD ${ddText(p.resources.dd6)}；雷电 ${p.resources.lightning}；充能 ${p.resources.nx_charge}；成熟炸药 ${p.resources.mature_bombs}；奖励 ${p.resources.reward_stock}`} onClick={()=>setResourcePlayer(p.player_id)} aria-label={`${p.nickname}的公开资源`}>DD {ddText(p.resources.dd6)}<small>雷 {p.resources.lightning} · 充 {p.resources.nx_charge} · 弹 {p.resources.mature_bombs} · 奖 {p.resources.reward_stock}</small></button></span></div>)}</div><section className="summary" aria-live="polite"><span className="eyebrow">公开战况 · 第 {view.turn_index} 拍</span><h2>{view.phase==='submitting'?'已提交，等待共同揭晓':view.phase==='revealed'?'本拍揭晓':view.phase==='error'?'提交未完成':view.options.length?'选择你的下一拍':'留在原席位，看看下一拍'}</h2><p>{view.summary[0]}</p><details><summary>展开本拍摘要</summary>{view.summary.slice(1).map((s,i)=><p key={i}>{s}</p>)}<small>局号：{view.game_id}</small></details></section></div>
   {self&&<section className="self-strip"><Avatar id={self.avatar_id}/><div><b>{self.nickname} · 本人</b><small>{self.alive?'仍在场':'已淘汰 · 等待下一场'}</small></div><div className="resources"><b title={`DD ${ddText(self.resources.dd6)}`}>DD <em>{ddText(self.resources.dd6)}</em></b><span>雷电 {self.resources.lightning}</span><span>聂湘充能 {self.resources.nx_charge}</span><span>炸药 成熟 {self.resources.mature_bombs}</span><span>奖励 {self.resources.reward_stock}</span><button className="resource-more" onClick={()=>setResourcePlayer(self.player_id)}>资源详情</button><span>强化削 {self.resources.enhanced_xiao?'有':'无'}</span><small>{view.summary.find(s=>s.startsWith('本人进度：'))}</small></div></section>}
   {!!view.options.length?<><div className="turn-strip"><span>{view.timer.mode==='untimed'?'练习：不限时':'计时示例 · 不会自动出牌'}</span><progress max={view.timer.total_ms||1} value={view.timer.remaining_ms??1}/><span>{view.submitted?'本人已提交':selected?`已选：${selected.name}`:'先选一张牌'}</span></div><div className="card-groups">{groups.map(group=><section className={`card-group ${group}`} key={group}><h3>{groupName[group]} <span>{view.options.filter(o=>o.ui_group===group).length}</span></h3><div className="cards">{ordered.filter(o=>o.ui_group===group).map(o=><article key={o.entry_id} className={`card ${o.available?'':'unavailable'} ${selected?.entry_id===o.entry_id?'selected':''}`} data-entry={o.entry_id}><button className="card-pick" disabled={!o.available||!editable} aria-pressed={selected?.entry_id===o.entry_id} aria-label={`选择 ${o.name}`} onClick={()=>choose(o.entry_id)}><span className="card-code">{o.doc_id} <span>{hotkeys.has(o.entry_id)?`键 ${hotkeys.get(o.entry_id)}`:'鼠标'}</span></span><strong>{o.name}</strong><span className="card-cost">实付 {o.cost_text}</span><span className="card-require">{o.requirement_text}</span><span className="card-state">{selected?.entry_id===o.entry_id?'已选中':o.available?'可用':reasons[o.reason_code||'']||'不可用'}</span></button><button className="card-info" aria-label={`${o.name}：详情与原因`} onClick={()=>setDetail(o)}>?</button></article>)}</div></section>)}</div><footer className="table-actions"><small>数字键 1–0 选择 · Enter 提交 · ? 查看门槛与条款</small><span>{ordered.filter(o=>o.available).length} / 33 可用</span><button disabled={sceneChangePending.current} onClick={()=>navigate(()=>setModal('leave'))}>离开牌桌</button><button className="primary" disabled={!editable||!selected} onClick={()=>void submit()}>{view.submitted?'已提交':view.phase==='error'?'重试提交':'提交所选'}</button></footer></>:<section className="spectating"><h2>{self?'你已淘汰，等待下一场。':'你正在观看公开演示。'}</h2><p>观战不显示手牌，也不接受选招快捷键。</p><button disabled={sceneChangePending.current} onClick={()=>void leave()}>退出观战</button></section>}
  </main>}
  {page==='result'&&view?.outcome&&<main className="center"><section className="paper results"><span className="eyebrow">P09 · 整场结果 · {live?'真实规则结算':'固定演示脚本'}</span><h1>{view.outcome.winner_id?'这一场，有人留下。':'全员淘汰，无人获胜。'}</h1>{view.outcome.winner_id&&<div className="winner"><Avatar id={view.participants.find(p=>p.player_id===view.outcome!.winner_id)?.avatar_id}/><h2>{view.participants.find(p=>p.player_id===view.outcome!.winner_id)?.nickname}</h2><p>唯一赢家</p></div>}<p>{live?'本场参赛名单':'演示参赛名单'} · {view.participants.length} 人</p><ul className="roster">{view.participants.map(p=><li key={p.player_id}>{p.nickname}<span>{p.player_id===view.outcome!.winner_id?'获胜':'已淘汰'}</span></li>)}</ul>{live?<details className="result-summary"><summary>查看最后一拍账目</summary>{view.summary.map((line,i)=><p key={i}>{line}</p>)}</details>:<p>这是脚本结果，未运行真实胜负逻辑。</p>}<button className="primary" disabled={busy} onClick={()=>view.participants.length===2?void start():void preview('initial')}>再来一场{view.participants.length===6?'预览':''}</button><button disabled={sceneChangePending.current} onClick={()=>void leave()}>返回主菜单</button></section></main>}
  {page==='settings'&&<main className="settings-layout"><nav>{['声音','窗口','昵称头像','关于'].map(t=><button key={t} aria-pressed={settingsTab===t} onClick={()=>setSettingsTab(t)}>{t}</button>)}<button onClick={closeSettings}>关闭设置</button></nav><section className="paper settings-content"><h1>{settingsTab}</h1><fieldset disabled={saving}>{settingsTab==='声音'?<><p>音源尚未加入。音量会真实保存，当前没有试听声音。</p>{(['music','effects'] as const).map(k=><label key={k}>{k==='music'?'音乐':'音效'} · {settings[k]}%<input type="range" aria-label={k==='music'?'音乐音量':'音效音量'} min="0" max="100" value={settings[k]} onChange={e=>setSettings({...settings,[k]:Number(e.target.value)})}/></label>)}</>:settingsTab==='窗口'?<><label className="checkbox"><input type="checkbox" checked={settings.fullscreen} onChange={e=>setSettings({...settings,fullscreen:e.target.checked})}/>保存后使用全屏</label><p>窗口模式可拖动边缘调整大小。目标内容区 1366×768 / 1920×1080。</p></>:settingsTab==='昵称头像'?<Identity nickname={nickname} avatar={avatar} onName={setNickname} onAvatar={setAvatar}/>:<><h2>叠叠 · R02-T04-a</h2><p>Electron 本地单人 · 经典规则 1.0.1</p><p>本机档案和设置可以保存。单人对局已接入真实规则和临时随机对手。联机、正式美术与音源仍待后续接入。</p><p>占位图形由本任务绘制；文字使用系统字体，不附带字体文件。</p></>}</fieldset><footer><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'保存中…':'保存并关闭'}</button><button disabled={saving} onClick={closeSettings}>关闭</button></footer></section></main>}
  {page==='manual'&&<main className="manual"><header><div><span className="eyebrow">P11 · 经典规则 1.0.1</span><h1>每一招，都有来处。</h1></div><button disabled={sceneChangePending.current} onClick={()=>navigate(()=>setPage(returnPage))}>返回</button></header><div className="manual-tools"><input aria-label="搜索招式" placeholder="搜索招式名称、说明…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="招式分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部 33 招</option>{groups.map(g=><option value={g} key={g}>{groupName[g]}</option>)}</select><button onClick={()=>setRule('all')}>完整条款 R01—R28</button></div><p>强化削：需持有 1/3 DD，实付 0。张新伟复制聂湘：不要求也不扣聂湘充能。</p><div className="manual-list">{manual?.entries.filter(o=>(category==='all'||o.ui_group===category)&&`${o.name}${o.description}`.toLowerCase().includes(search.toLowerCase())).map(o=><button key={o.entry_id} onClick={()=>setDetail(o)}><small>{o.doc_id} · {groupName[o.ui_group]}</small><h3>{o.name}</h3><p>{o.description}</p><small>费用：{o.cost_text}</small></button>)}</div>{manual&&!manual.entries.some(o=>(category==='all'||o.ui_group===category)&&`${o.name}${o.description}`.toLowerCase().includes(search.toLowerCase()))&&<p>没有匹配的招式，试试别的名称。</p>}</main>}
  {modal&&<Modal title={modal==='preview'?'开发场景':modal==='settings-close'?'还有未保存的修改':modal==='recover'?'备份并重建档案':modal==='online'?'好友联机尚未加入':'离开当前对局'} closeDisabled={sceneChangePending.current||saving} onClose={()=>navigate(()=>{if(!saving)setModal('');})}>
   {error&&<p role="alert">{error}</p>}{modal==='preview'?<><p>这里是固定脚本演示，尚未开放多人对战。切换场景将结束当前对局，进度不会保存。</p><div className="scene-grid">{([['initial','P07 · 初始 A / 12 可用'],['midgame','P07 · 中局 B / 26 可用'],['spectator','P08 · 普通观众'],['eliminated','P08 · 本人已淘汰'],['restart','P08 · 淘汰后存活者新局'],['winner','P09 · 唯一赢家'],['draw','P09 · 全员淘汰'],['invalid','P07 · 提交失败后重试']] as [Scene,string][]).map(([s,label])=><button key={s} disabled={busy} aria-pressed={scene===s} onClick={()=>void preview(s)}>{label}</button>)}</div></>:modal==='settings-close'?<><p>可以继续编辑，也可以保存或放弃这次修改。</p><button onClick={()=>setModal('')}>继续编辑</button><button disabled={saving} onClick={()=>{setModal('');setPage(returnPage);setError('');}}>不保存关闭</button><button className="primary" disabled={saving} onClick={()=>void save()}>保存关闭</button></>:modal==='recover'?<><p>先备份损坏的原文件，再创建新档案。原昵称和设置不会自动迁移。</p><button disabled={saving} onClick={()=>setModal('')}>继续检查</button><button className="primary" disabled={saving} onClick={()=>void save(true)}>确认备份并重建</button></>:modal==='online'?<><p>P04 / P05 房间功能留待后续开发，当前不能创建或加入房间。</p><button className="primary" onClick={()=>setModal('')}>知道了，返回</button></>:<><p>本次对局进度不会保存。本机档案和设置仍保留。</p><button onClick={()=>setModal('')}>继续{live?'对局':'演示'}</button><button className="primary" disabled={sceneChangePending.current} onClick={()=>void leave()}>离开</button></>}
  </Modal>}
  {detail&&<Modal title={`${detail.doc_id} · ${detail.name}`} onClose={()=>setDetail(null)}><p>{detailEntry?.description}</p><dl><dt>需要持有 / 资格</dt><dd>{detail.requirement_text}</dd><dt>实际花费</dt><dd>{detail.cost_text}</dd><dt>{page==='manual'?'开局示例状态':live?'本拍真实资格':'此静态样例的状态'}</dt><dd>{detail.available?'可用':reasons[detail.reason_code||'']||'不可用'}</dd></dl>{detail.entry_id==='ZhangXinWei'&&<p>复制聂湘也不需充能，实际充能支出为 0；仍须本局未用且有有效复制记录。</p>}<button onClick={()=>{setRule(detail.detail_rule_ids[0]);setDetail(null);}}>阅读条款 {detail.detail_rule_ids.join(' / ')}</button></Modal>}
  {resourceDetail&&<Modal title={`${resourceDetail.nickname} · 公开资源`} onClose={()=>setResourcePlayer('')}><dl>{Object.entries({DD:ddText(resourceDetail.resources.dd6),雷电:resourceDetail.resources.lightning,聂湘充能:resourceDetail.resources.nx_charge,成熟炸药:resourceDetail.resources.mature_bombs,奖励:resourceDetail.resources.reward_stock,强化削:resourceDetail.resources.enhanced_xiao?'有':'无',云使用次数:resourceDetail.resources.cloud_uses,田利军使用次数:resourceDetail.resources.tian_uses,炸药放置次数:resourceDetail.resources.bomb_placement_count}).map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{value}</dd></React.Fragment>)}</dl><p>{view?.summary.find(line=>line.startsWith(resourceDetail.player_id===view.self_id?'本人进度：':`${resourceDetail.nickname}进度：`))}</p></Modal>}
  {rule&&<Modal title="本地完整条款 · 经典规则 1.0.1" onClose={()=>setRule('')}><nav className="rule-nav">{manual?.sections.map(s=><button key={s.id} aria-pressed={rule===s.id} onClick={()=>setRule(s.id)}>{s.id}</button>)}</nav>{manual?.sections.filter(s=>rule==='all'||rule===s.id).map(s=><section key={s.id}><h3>{s.id}</h3><pre>{s.text}</pre></section>)}</Modal>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
