const { _electron: electron }=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const {execFileSync}=require('node:child_process');
const output=path.resolve('../../docs/results/R02-T03-a');
(async()=>{
 await fs.mkdir(output,{recursive:true});
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'deidei-r02-ui-'));
 const env={...process.env,DEIDEI_TEST_DATA_DIR:directory};delete env.ELECTRON_RUN_AS_NODE;
 let app;
 const evidence={tested_code_sha:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),uncommitted:execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim().length>0,platform:process.platform,arch:process.arch,checks:[],screenshots:[]};
 const passed=s=>{evidence.checks.push(s);console.log('PASS',s);};
 try {
  app=await electron.launch({args:['.'],env});
  let page=await app.firstWindow();page.setDefaultTimeout(10000);
  const consoleErrors=[];page.on('pageerror',e=>consoleErrors.push(e.message));
  await page.getByRole('heading',{name:'先写下你的名字。'}).waitFor();
  evidence.native=await app.evaluate(({BrowserWindow,screen})=>({contentBounds:BrowserWindow.getAllWindows()[0].getContentBounds(),displays:screen.getAllDisplays().map(d=>({bounds:d.bounds,workArea:d.workArea,scaleFactor:d.scaleFactor})),versions:process.versions}));
  const shot=async(name)=>{await page.screenshot({path:path.join(output,`${name}.png`),scale:'css'});evidence.screenshots.push({name,viewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio})),method:'Playwright screenshot of real Electron renderer, CSS-pixel scale; viewport may be emulated'});};
  await shot('P01-native');
  await page.getByRole('button',{name:'保存，进入课间 →'}).click();await page.getByRole('alert').waitFor();
  await page.getByRole('textbox',{name:'昵称',exact:true}).fill('纸上测试');
  await page.getByRole('button',{name:'头像：月亮'}).click();
  await page.getByRole('button',{name:'保存，进入课间 →'}).click();await page.getByRole('button',{name:'单人演示'}).waitFor();
  passed('P01 rejects empty nickname, creates local profile and enters P02');await shot('P02-menu');
  const security=await page.evaluate(async()=>({node:typeof window.require,process:typeof window.process,keys:Object.keys(window.desktop),extra:await window.desktop.profile.create({nickname:'x',avatar_id:'leaf',local_id:'../../bad'}),oversize:await window.desktop.profile.update({nickname:'x'.repeat(5000),avatar_id:'leaf'}),badSettings:await window.desktop.settings.apply({nickname:'x',avatar_id:'leaf',settings:{music:true,effects:50,fullscreen:false}})}));
  assert.equal(security.node,'undefined');assert.equal(security.process,'undefined');assert.equal(security.extra.ok,false);assert.equal(security.oversize.ok,false);assert.equal(security.badSettings.ok,false);
  const prefs=await app.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:p.sandbox,nodeIntegration:p.nodeIntegration,contextIsolation:p.contextIsolation,webSecurity:p.webSecurity};});
  assert.deepEqual(prefs,{sandbox:true,nodeIntegration:false,contextIsolation:true,webSecurity:true});evidence.security={...security,prefs};passed('sandbox and preload isolation, unknown fields and oversized IPC rejected');
  const boundary=await app.evaluate(async({BrowserWindow,net},preloadPath)=>{
    const other=new BrowserWindow({show:false,webPreferences:{preload:preloadPath,sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});
    await other.loadURL('app://desktop/index.html');
    const denied=await other.webContents.executeJavaScript('window.desktop.profile.read()');other.destroy();
    const missing=await net.fetch('app://desktop/profile.json');
    const method=await net.fetch('app://desktop/index.html',{method:'POST'});
    return {denied,unlistedStatus:missing.status,postStatus:method.status};
  },path.join(__dirname,'preload.cjs'));
  assert.equal(boundary.denied.error,'INVALID_SENDER');assert.equal(boundary.unlistedStatus,403);assert.equal(boundary.postStatus,403);evidence.boundary=boundary;
  await page.evaluate(()=>window.open('https://example.invalid/'));
  assert.equal((await app.windows()).length,1);passed('other renderer sender, unlisted local resources, non-GET and popup denied');
  await page.getByRole('button',{name:'好友联机'}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'知道了，返回'}).click();passed('P04/P05 honestly explain unavailable networking');
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'昵称头像',exact:true}).click();
  await page.getByRole('textbox',{name:'昵称',exact:true}).fill('修改未保存');
  const profileDir=path.join(directory,'local-profile'),file=path.join(profileDir,'profile.json'),old=await fs.readFile(file);
  await fs.chmod(profileDir,0o500);
  await page.getByRole('button',{name:'保存并关闭',exact:true}).click();await page.getByRole('alert').waitFor();
  assert.equal(await page.getByRole('textbox',{name:'昵称',exact:true}).inputValue(),'修改未保存');assert.deepEqual(await fs.readFile(file),old);await shot('P10-save-failure');
  await fs.chmod(profileDir,0o700);
  await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:'昵称',exact:true}).inputValue(),'修改未保存');
  await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'不保存关闭',exact:true}).click();assert.deepEqual(await fs.readFile(file),old);
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'声音',exact:true}).click();await page.getByRole('slider',{name:'音乐音量'}).fill('25');await page.getByRole('button',{name:'保存并关闭',exact:true}).click();assert.equal(JSON.parse(await fs.readFile(file,'utf8')).settings.music,25);passed('P10 real permission failure retains input and old file; continue, discard and save work');
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'窗口',exact:true}).click();await page.getByRole('checkbox',{name:'保存后使用全屏'}).check();await page.getByRole('button',{name:'保存并关闭',exact:true}).click();
  await page.getByRole('button',{name:'单人演示'}).waitFor();
  await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];if(!w.isFullScreen())await new Promise(resolve=>w.once('enter-full-screen',resolve));});
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),true);
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'窗口',exact:true}).click();await page.getByRole('checkbox',{name:'保存后使用全屏'}).uncheck();await page.getByRole('button',{name:'保存并关闭',exact:true}).click();
  await page.getByRole('button',{name:'单人演示'}).waitFor();
  await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];if(w.isFullScreen())await new Promise(resolve=>w.once('leave-full-screen',resolve));});
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),false);passed('P10 window setting enters and leaves actual macOS fullscreen');
  await page.getByRole('button',{name:'经典规则手册',exact:true}).click();await page.getByRole('textbox',{name:'搜索招式'}).fill('聂湘');assert.ok(await page.locator('.manual-list button').count()>=2);await shot('P11-manual');
  await page.getByRole('button',{name:'完整条款 R01—R28'}).click();assert.equal(await page.locator('.rule-nav button').count(),28);await page.keyboard.press('Escape');await page.getByRole('button',{name:'返回',exact:true}).click();passed('P11 search and 28 local rule sections');
  await page.getByRole('button',{name:'单人演示'}).click();await shot('P03-prepare');await page.getByRole('button',{name:'进入双人演示'}).click();await page.locator('.card').first().waitFor();
  await page.setViewportSize({width:1366,height:768});
  assert.equal(await page.locator('.card').count(),33);assert.equal(await page.locator('.card:not(.unavailable)').count(),12);
  await page.keyboard.press('1');const selected=await page.locator('.card.selected').getAttribute('data-entry');assert.ok(selected);assert.equal((await page.evaluate(()=>window.desktop.port.getView())).data.submitted,false);
  await page.getByRole('button',{name:'开发预览',exact:true}).click();await page.keyboard.press('2');await page.keyboard.press('Enter');assert.equal((await page.evaluate(()=>window.desktop.port.getView())).data.submitted,false);await page.keyboard.press('Escape');
  await shot('P06-selected');await page.keyboard.press('Enter');await page.locator('[data-phase="submitting"]').waitFor();await page.keyboard.press('Enter');await shot('P06-submitted');
  await page.locator('[data-phase="revealed"]').waitFor();await shot('P06-revealed');await page.getByRole('heading',{name:'这一场，有人留下。'}).waitFor();assert.equal(await page.locator('.roster li').count(),2);await shot('P09-solo-winner');passed('P06 keyboard selects before submitting; modal blocks keys; submitting → revealed → P09, two-person roster');
  const scene=async(label)=>{await page.getByRole('button',{name:'开发预览',exact:true}).click();await page.getByRole('button',{name:label,exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});};
  await scene('P07 · 中局 B / 26 可用');assert.equal(await page.locator('.card:not(.unavailable)').count(),26);
  for(const width of [1366,1920]){
   const height=width===1366?768:1080;await page.setViewportSize({width,height});
   const layout=await page.evaluate(()=>({viewport:[innerWidth,innerHeight],body:[document.documentElement.scrollWidth,document.documentElement.scrollHeight],cards:[...document.querySelectorAll('.card')].map(el=>{const r=el.getBoundingClientRect(),name=el.querySelector('strong');return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,name:getComputedStyle(name).fontSize,cost:getComputedStyle(el.querySelector('.card-cost')).fontSize};})}));
   assert.equal(layout.cards.length,33);assert.ok(layout.cards.every(c=>c.x>=0&&c.right<=width&&c.bottom<=height));assert.ok(layout.body[0]<=width&&layout.body[1]<=height,JSON.stringify(layout.body));assert.ok(layout.cards.every(c=>parseFloat(c.name)>=16&&parseFloat(c.cost)>=12));
   assert.equal(new Set(layout.cards.map(c=>Math.round(c.y))).size,3);
   evidence[`layout_${width}`]=layout;await shot(`P07-midgame-${width}x${height}`);
  }
  passed('33 visible cards in three rows at both target viewports, no page overflow, names >=16px costs >=12px');
  await page.setViewportSize({width:1366,height:768});const positions=await page.locator('.card').evaluateAll(els=>els.map(e=>e.getAttribute('data-entry')));
  await page.locator('[data-entry="Bi"] .card-pick').click();assert.deepEqual(await page.locator('.card').evaluateAll(els=>els.map(e=>e.getAttribute('data-entry'))),positions);
  assert.equal(await page.locator('[data-entry="Shell"] .card-pick').isDisabled(),true);await page.locator('[data-entry="Shell"] .card-info').click();await page.getByRole('dialog').waitFor();assert.ok((await page.getByRole('dialog').innerText()).includes('DD 不足'));await page.keyboard.press('Escape');passed('selection does not reorder cards; grey cards disabled with accessible reason dialog');
  await scene('P07 · 初始 A / 12 可用');await shot('P07-initial-1366x768');
  await scene('P07 · 提交失败后重试');await page.keyboard.press('1');await page.keyboard.press('Enter');await page.locator('[data-phase="error"]').waitFor();assert.equal(await page.locator('.card.selected').count(),1);await shot('P07-submit-error');await page.getByRole('button',{name:'重试提交',exact:true}).click();await page.locator('[data-phase="submitting"]').waitFor();passed('script rejection retains selected card and supports retry');
  for(const [label,name] of [['P08 · 普通观众','P08-spectator'],['P08 · 本人已淘汰','P08-eliminated'],['P08 · 淘汰后存活者新局','P08-restart']]){
   await scene(label);assert.equal(await page.locator('.card').count(),0);await page.keyboard.press('1');await page.keyboard.press('Enter');assert.equal((await page.evaluate(()=>window.desktop.port.getView())).data.submitted,false);await shot(name);
  }passed('P08 spectator/eliminated/restart hide cards, block shortcuts, preserve eliminated seats');
  await scene('P09 · 全员淘汰');await page.getByRole('heading',{name:'全员淘汰，无人获胜。'}).waitFor();assert.equal(await page.locator('.roster li').count(),6);await shot('P09-draw');
  await scene('P09 · 唯一赢家');assert.equal(await page.locator('.winner').count(),1);await shot('P09-six-winner');
  await page.getByRole('button',{name:'返回主菜单',exact:true}).click();
  await page.getByRole('button',{name:'单人演示'}).click();await page.getByRole('button',{name:'进入双人演示'}).click();await page.locator('.card').first().waitFor();
  await page.keyboard.down('1');await page.keyboard.down('1');await page.keyboard.up('1');assert.equal((await page.evaluate(()=>window.desktop.port.getView())).data.submitted,false);
  await page.getByRole('button',{name:'离开牌桌',exact:true}).click();await page.getByRole('button',{name:'继续演示',exact:true}).click();assert.equal(await page.locator('.card').count(),33);
  await page.getByRole('button',{name:'离开牌桌',exact:true}).click();await page.getByRole('button',{name:'离开',exact:true}).click();await page.getByRole('button',{name:'单人演示'}).waitFor();passed('held number key never submits; leave confirmation supports cancel and leave');
  await app.close();app=null;
  app=await electron.launch({args:['.'],env});page=await app.firstWindow();await page.getByRole('button',{name:'单人演示'}).waitFor();const restored=await page.evaluate(()=>window.desktop.profile.read());assert.equal(restored.data.nickname,'纸上测试');assert.equal(restored.data.settings.music,25);passed('real Electron restart restores profile and settings');
  assert.deepEqual(consoleErrors,[]);passed('no renderer page errors');
  evidence.status='PASS';
 } catch(e){evidence.status='FAIL';evidence.error=e.stack;throw e;}
 finally{await fs.writeFile(path.join(output,'ui-evidence.json'),JSON.stringify(evidence,null,2)+'\n');if(app)await app.close();await fs.chmod(path.join(directory,'local-profile'),0o700).catch(()=>{});await fs.rm(directory,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
