// Actual first-entry screen and quit flow, isolated from the user's local profile.
const {_electron:electron}=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {sourceInput,captureDiagnostics}=require('./smoke-performance.cjs');
(async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'deidei-entry-'));
 const output=path.resolve(process.env.DEIDEI_SMOKE_OUTPUT||path.join(__dirname,'../../docs/results/R04-T01-b/entry-ui'));
 const input=sourceInput();
 await fs.mkdir(output,{recursive:true});
 const env={...process.env,DEIDEI_TEST_DATA_DIR:directory};delete env.ELECTRON_RUN_AS_NODE;
 let app,page,failure,lastState,checks=0;const errors=[];
 const check=(value,message)=>{assert.ok(value,message);checks++;};
 try{
  app=await electron.launch({args:[path.join(__dirname,'smoke-live-main.cjs')],env});
  page=await app.firstWindow();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
  await page.locator('.welcome-scene[data-stage=opening]').waitFor();
  await page.waitForFunction(()=>document.querySelector('video')?.currentTime>1);
  const media=await page.locator('video').evaluate(v=>({width:v.videoWidth,height:v.videoHeight,error:v.error?.message,muted:v.muted}));
  check(media.width===1920&&media.height===1080&&!media.error&&media.muted,'real cropped video decodes and advances '+JSON.stringify(media));
  check(await page.locator('.scene-world').evaluate(n=>Math.abs(new DOMMatrix(getComputedStyle(n).transform).a-1.04)<.0001),'opening holds the exported tail-frame camera');
  await page.screenshot({path:path.join(output,'welcome-opening.png')});
  await page.getByRole('button',{name:'开启开场声音',exact:true}).click();
  check(await page.locator('video').evaluate(v=>!v.muted),'opening sound toggle unmutes video');
  await page.locator('.welcome-scene[data-stage=title]').waitFor();
  check(await page.locator('video').evaluate(v=>v.ended&&v.paused),'natural end transitions to title');
  check(await page.getByRole('button',{name:'重播开场',exact:true}).isVisible(),'first-entry title also allows replay');
  await page.waitForTimeout(450);
  check((await page.evaluate(()=>window.desktop.profile.read())).data===null,'first entry has no profile');
  // The shared hall now keeps the character mounted but hidden until entrance.
  check(await page.locator('.scene-character').evaluate(n=>getComputedStyle(n).opacity==='0'),'title delays character appearance');
  check(await page.locator('.menu-environment').evaluate(n=>getComputedStyle(n).animationName==='none'),'title does not inherit the menu camera drift');
  check(await page.locator('.welcome-scene').evaluate(n=>/rgba\(3,\s*10,\s*18,\s*0\.65/.test(getComputedStyle(n,'::before').backgroundImage)&&getComputedStyle(n,'::before').opacity==='1'),'title preserves the exported tail-frame lighting');
  check(await page.locator('.scene-world').evaluate(n=>Math.abs(new DOMMatrix(getComputedStyle(n).transform).a-1.04)<.0001),'video to title keeps the same camera scale');
  await page.screenshot({path:path.join(output,'welcome-title.png'),scale:'css'});
  await page.getByRole('button',{name:'进入牌厅',exact:true}).click();
  await page.locator('.welcome-scene[data-stage=flip]').waitFor();
  check(await page.getByRole('textbox',{name:'昵称',exact:true}).count()===0,'form appears after flip');
  await page.getByRole('heading',{name:'这张牌，属于你。',exact:true}).waitFor();
  await page.waitForFunction(()=>new DOMMatrix(getComputedStyle(document.querySelector('.scene-world')).transform).a>1.1127);
  check(await page.locator('.scene-world').evaluate(n=>getComputedStyle(n).filter.includes('6px')),'name entry already zooms and blurs the hall background');
  check(await page.locator('.welcome-glass').evaluate(n=>getComputedStyle(n).backdropFilter==='none'),'incoming hall components do not require a full-screen backdrop blur');
  const nameCamera=await page.locator('.scene-world').evaluate(n=>({transform:getComputedStyle(n).transform,filter:getComputedStyle(n).filter}));
  check(await page.locator('.welcome-tools>strong,.welcome-title>span,.welcome-preview-note').count()===0,'redundant welcome labels removed');
  // Round 2: cosmetic expectations follow Teddy's chosen input and text-action design.
  check(await page.locator('.welcome-card-kicker').count()===0,'first-card kicker removed');
  check(await page.getByText('1—20 个字，仅保存在这台电脑。',{exact:true}).count()===0,'welcome has no redundant nickname hint');
  const fieldSkin=()=>page.locator('.ui-input-field').evaluate(n=>{const s=getComputedStyle(n);return [s.backgroundImage,s.borderRadius,s.height,s.borderColor,s.boxShadow];});
  await page.getByRole('textbox',{name:'昵称',exact:true}).blur();
  await page.mouse.move(0,0);await page.waitForFunction(()=>document.querySelector('.ui-input-field').getAnimations().length===0);
  const nicknameSkin=await fieldSkin();
  const reload=page.getByRole('button',{name:'重新读取',exact:true});
  await reload.hover();await page.waitForTimeout(250);
  check(await reload.evaluate(n=>{const s=getComputedStyle(n);return s.backgroundColor==='rgba(0, 0, 0, 0)'&&s.backgroundImage==='none'&&s.borderWidth==='0px'&&s.padding==='0px';}),'reload hover only affects the text, with no background, border or padded hit area');
  await reload.focus();await page.keyboard.press('Shift+Tab');await page.keyboard.press('Tab');
  check(await reload.evaluate(n=>getComputedStyle(n).textDecorationLine.includes('underline')),'text action has a visible keyboard focus underline');
  await page.getByRole('button',{name:'确认名字',exact:true}).click();
  await page.getByRole('alert').waitFor();
  check(await page.getByRole('alert').innerText()==='昵称须为 1—20 个字，不能包含控制字符。','nickname error has no avatar instruction');
  check(await page.getByRole('alert').evaluate(n=>{const s=getComputedStyle(n);return n.closest('label')!==null&&s.backgroundImage==='none'&&s.backgroundColor==='rgba(0, 0, 0, 0)'&&s.borderWidth==='0px';}),'validation message sits under the nickname field without a surface');
  await page.screenshot({path:path.join(output,'welcome-name-validation.png'),scale:'css'});
  await page.getByRole('textbox',{name:'昵称',exact:true}).fill('档案保留验收');
  await page.getByRole('button',{name:'确认名字',exact:true}).click();
  await page.getByRole('heading',{name:'从哪开始？',exact:true}).waitFor();
  await page.waitForTimeout(550);
  check(await page.locator('.scene-world').evaluate((n,before)=>{const s=getComputedStyle(n);return s.transform===before.transform&&s.filter===before.filter&&n.getAnimations().length===0;},nameCamera),'confirming the name keeps the background camera and blur stationary');
  check(await page.locator('.welcome-guide').evaluate(n=>n.getBoundingClientRect().height>=76),'new-player guide is the large primary action');
  check(await page.getByRole('radio').count()===3&&await page.getByRole('radio',{name:'新手',exact:true}).isChecked(),'three experience levels default to beginner');
  await page.getByRole('radio',{name:'新手',exact:true}).focus();await page.keyboard.press('ArrowRight');
  check(await page.getByRole('radio',{name:'熟悉',exact:true}).isChecked()&&await page.getByRole('button',{name:'进入牌厅',exact:true}).isVisible(),'native arrow keys select familiar and skip the tutorial');
  await page.keyboard.press('ArrowRight');
  check(await page.getByRole('radio',{name:'高手',exact:true}).isChecked()&&await page.getByRole('button',{name:'进入牌厅',exact:true}).isVisible(),'expert also enters the hall directly');
  await page.getByRole('radio',{name:'新手',exact:true}).check();
  await page.screenshot({path:path.join(output,'welcome-ready.png'),scale:'css'});
  await page.getByRole('button',{name:'开始新手指引',exact:true}).click();
  await page.locator('.battle-table[data-ready=true]').waitFor();
  check((await page.evaluate(()=>window.desktop.port.getView())).data.source==='live','welcome starts actual tutorial worker');
  await page.getByRole('button',{name:'暂停',exact:true}).click();
  await page.getByRole('button',{name:'退出游戏 LEAVE MATCH',exact:true}).click();
  await page.getByRole('dialog',{name:'离开当前对局',exact:true}).getByRole('button',{name:'离开',exact:true}).click();
  await page.locator('.menu-layout').waitFor();
  await page.getByRole('button',{name:'经典规则手册 R',exact:true}).click();
  await page.getByRole('textbox',{name:'搜索招式',exact:true}).waitFor();
  await page.mouse.move(0,0);await page.waitForTimeout(700);
  assert.deepEqual(await fieldSkin(),nicknameSkin);checks++;
  await page.getByRole('textbox',{name:'搜索招式',exact:true}).fill('bi');
  await page.getByRole('button',{name:'清空搜索',exact:true}).click();
  check(await page.getByRole('textbox',{name:'搜索招式',exact:true}).inputValue()==='','shared search keeps its clear action');
  await page.screenshot({path:path.join(output,'shared-archive-search.png'),scale:'css'});
  await page.getByRole('button',{name:/返回主菜单/}).click();
  await page.locator('.app[data-page=menu]').waitFor();
  await page.getByRole('button',{name:'设置 S',exact:true}).click();
  await page.getByRole('button',{name:'昵称头像',exact:false}).click();
  await page.getByRole('textbox',{name:'昵称',exact:true}).waitFor();
  check(await page.locator('.ui-input-field>input').count()===1,'settings nickname uses the shared field');
  await page.getByRole('button',{name:/声音 AUDIO/}).click();
  await page.getByRole('button',{name:/返回主菜单/}).click();
  await page.locator('.app[data-page=menu]').waitFor();
  const profile=(await page.evaluate(()=>window.desktop.profile.read())).data;
  await page.getByRole('button',{name:'退出 Q',exact:true}).click();
  await page.getByRole('dialog',{name:'退出游戏？',exact:true}).waitFor();
  check(!page.isClosed(),'quit button only opens confirmation');
  await page.screenshot({path:path.join(output,'quit-confirmation.png')});
  await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  check(await page.getByRole('button',{name:'退出 Q',exact:true}).evaluate(n=>n===document.activeElement),'quit cancellation restores focus');
  await page.getByRole('button',{name:'退出 Q',exact:true}).click();
  await page.getByRole('button',{name:'继续留在游戏',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'hidden'});check(await page.locator('.menu-layout').isVisible(),'continue keeps menu open');
  await page.getByRole('button',{name:'开发预览',exact:true}).click();
  await page.getByRole('button',{name:'P01 · 首次进入／欢迎建档',exact:true}).click();
  await page.getByRole('button',{name:'跳过开场'}).click();
  check(await page.locator('video').evaluate(v=>v.paused),'skip pauses video');
  await page.getByRole('button',{name:'重播开场',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('video')?.currentTime>.3);
  check(await page.locator('.welcome-scene[data-stage=opening]').count()===1,'replay restarts real video');
  await page.locator('video').evaluate(v=>{v.src='assets/menu/unknown.mp4';v.load();});
  await page.locator('.welcome-scene[data-stage=title]').waitFor();
  check(await page.locator('video').evaluate(v=>v.paused),'missing media falls back to title');
  await page.getByRole('button',{name:'进入牌厅',exact:true}).click();await page.getByRole('heading',{name:'这张牌，属于你。',exact:true}).waitFor();
  check(await page.getByRole('button',{name:'确认名字',exact:true}).count()===0,'preview has no save action');
  await page.getByRole('textbox',{name:'昵称',exact:true}).fill('不应写入档案');
  await page.getByRole('button',{name:'头像：星星',exact:true}).click();
  for(const [width,height] of [[1000,650],[1366,768],[1920,1080]]){
   await app.evaluate(({BrowserWindow},{width,height})=>BrowserWindow.getAllWindows()[0].setContentSize(width,height),{width,height});
   await page.waitForTimeout(650);
   const fit=await page.locator('.welcome-card').evaluate(n=>{const r=n.getBoundingClientRect();return {fits:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&document.scrollingElement.scrollWidth<=innerWidth&&document.scrollingElement.scrollHeight===innerHeight,rect:[r.left,r.top,r.right,r.bottom],viewport:[innerWidth,innerHeight]};});
   check(fit.fits,'welcome preview fits '+width+' '+JSON.stringify(fit));
   await page.screenshot({path:path.join(output,`welcome-preview-${width}.png`)});
  }
  await page.getByRole('button',{name:'确认名字 · 仅预览',exact:true}).click();
  await page.getByRole('heading',{name:'从哪开始？',exact:true}).waitFor();
  assert.deepEqual((await page.evaluate(()=>window.desktop.profile.read())).data,profile);checks++;
  const background=await page.locator('.scene-world').elementHandle();
  const pivot=await background.evaluate(n=>getComputedStyle(n).transformOrigin);
  // Sample both sides of the profile -> menu handoff, not just its final frame.
  await page.getByRole('radio',{name:'熟悉',exact:true}).check();
  await page.locator('.welcome-guide').evaluate(button=>button.addEventListener('click',()=>{window.__welcomeMotion=[];const start=performance.now();function frame(){const world=getComputedStyle(document.querySelector('.scene-world'));const image=getComputedStyle(document.querySelector('.menu-environment'));window.__welcomeMotion.push({t:performance.now()-start,page:document.querySelector('.app').dataset.page,origin:world.transformOrigin,image:[...new DOMMatrix(image.transform).toFloat64Array()]});if(performance.now()-start<2200)requestAnimationFrame(frame);}frame();},{once:true}));
  await page.locator('.welcome-guide').click();
  await page.locator('.welcome-scene[data-stage=entering]').waitFor();
  check(await page.locator('.menu-layout').evaluate(n=>n.inert),'menu cannot be selected during docking');
  await page.waitForFunction(()=>document.querySelector('.welcome-scene')?.dataset.stage==='entering'&&Number(getComputedStyle(document.querySelector('.menu-rail')).opacity)>0);
  check(await page.locator('.scene-character').evaluate(n=>Number(getComputedStyle(n).opacity)>0),'hall character arrives while card is still docking');
  check(await page.locator('.menu-rail').evaluate(n=>{const r=n.getBoundingClientRect();return Number(getComputedStyle(n).opacity)>0&&r.top>=0&&r.bottom<=innerHeight;}),'hall navigation is visible inside the viewport while card is still docking');
  await page.screenshot({path:path.join(output,'welcome-menu-transition.png')});
  await page.locator('.app[data-page=menu]').waitFor();
  check(await background.evaluate(n=>n.isConnected),'same hall background survives welcome to menu');
  await page.waitForFunction(()=>window.__welcomeMotion?.at(-1)?.page==='menu');
  const motion=await page.evaluate(()=>window.__welcomeMotion);
  const boundary=motion.findIndex((v,i)=>i>0&&v.page==='menu'&&motion[i-1].page==='profile');
  check(boundary>0&&motion.every(v=>v.origin===pivot),'camera pivot stays fixed throughout the handoff '+JSON.stringify({pivot,boundary,origins:[...new Set(motion.map(v=>v.origin))]}));
  check(boundary>0&&motion[boundary].image.every((n,i)=>Math.abs(n-motion[boundary-1].image[i])<.01),'ambient camera does not jump when the welcome overlay unmounts');
  check(await page.locator('.scene-world').evaluate(n=>getComputedStyle(n).filter==='none'),'hall background returns to sharp focus');
  check(await page.locator('.menu-option').first().evaluate(n=>n===document.activeElement),'menu entrance restores keyboard focus');
  assert.deepEqual((await page.evaluate(()=>window.desktop.profile.read())).data,profile);checks++;
  await page.getByRole('button',{name:'开发预览',exact:true}).click();
  await page.getByRole('button',{name:'P01 · 首次进入／欢迎建档',exact:true}).click();
  await page.getByRole('button',{name:'跳过开场'}).click();
  await page.getByRole('button',{name:'进入牌厅',exact:true}).click();
  await page.getByRole('heading',{name:'这张牌，属于你。',exact:true}).waitFor();
  await page.getByRole('textbox',{name:'昵称',exact:true}).fill('不应写入档案');
  await page.getByRole('button',{name:'确认名字 · 仅预览',exact:true}).click();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'开发预览',exact:true}).click();
  await page.getByRole('button',{name:'P01 · 首次进入／欢迎建档',exact:true}).click();
  await page.locator('.welcome-scene[data-stage=title]').waitFor();
  check(await page.locator('video').evaluate(v=>v.paused&&v.currentTime===0),'reduced motion bypasses opening video');
  await page.getByRole('button',{name:'进入牌厅',exact:true}).click();
  await page.getByRole('textbox',{name:'昵称',exact:true}).waitFor({timeout:500});
  check(await page.getByRole('textbox',{name:'昵称',exact:true}).evaluate(n=>n===document.activeElement),'reduced motion enters form directly and focuses name');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.getByRole('button',{name:'结束预览，返回主菜单',exact:true}).click();
  assert.deepEqual((await page.evaluate(()=>window.desktop.profile.read())).data,profile);checks++;
  await page.getByRole('button',{name:'开发预览',exact:true}).click();
  await page.getByRole('button',{name:'P01 · 首次进入／欢迎建档',exact:true}).click();
  await page.getByRole('button',{name:'开发预览',exact:true}).click();
  await page.getByRole('button',{name:'P09 · 唯一赢家',exact:true}).click();
  await page.locator('.result-actions button').filter({hasText:'返回主菜单'}).click();
  await page.locator('.menu-layout').waitFor();
  await page.getByRole('button',{name:'设置 S',exact:true}).click();
  await page.getByRole('slider',{name:'音乐音量',exact:true}).fill('25');
  await page.getByRole('button',{name:'保存并关闭',exact:true}).click();
  await page.locator('.menu-layout').waitFor();
  const saved=(await page.evaluate(()=>window.desktop.profile.read())).data;
  check(saved.settings.music===25,'leaving welcome through another preview does not block real settings save');
  check(saved.nickname===profile.nickname&&saved.avatar_id===profile.avatar_id,'preview never overwrites identity');
  await page.getByRole('button',{name:'经典规则手册 R',exact:true}).click();
  await page.getByRole('button',{name:'新手实战',exact:true}).click();
  await page.locator('.battle-table[data-ready=true]').waitFor();
  await page.locator('.card[data-entry=Charge] .card-pick').click();
  const view=(await page.evaluate(()=>window.desktop.port.getView())).data;
  await page.getByRole('button',{name:'暂停',exact:true}).click();
  await page.getByRole('button',{name:'退出游戏 LEAVE MATCH',exact:true}).click();
  await page.getByRole('dialog',{name:'离开当前对局',exact:true}).waitFor();
  check((await page.evaluate(()=>window.desktop.port.getView())).data.view_id===view.view_id,'exit confirmation retains current match');
  await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  check(await page.locator('.card[data-entry=Charge]').getAttribute('class').then(c=>c.includes('selected')),'cancel retains chosen card');
  await page.getByRole('button',{name:'暂停',exact:true}).click();
  await page.getByRole('button',{name:'退出游戏 LEAVE MATCH',exact:true}).click();
  await page.getByRole('dialog',{name:'离开当前对局',exact:true}).getByRole('button',{name:'离开',exact:true}).click();
  await page.locator('.menu-layout').waitFor();check(await page.getByRole('region',{name:'新手实战指导'}).count()===0,'confirmed leave ends tutorial');
  const longName='一二三四五六七八九十一二三四五六七八九十';
  const renamed=await page.evaluate(n=>window.desktop.profile.update({nickname:n,avatar_id:'leaf'}),longName);
  check(renamed.ok,'isolated long identity saved');
  check(errors.length===0,'renderer errors: '+errors.join(';'));
  await page.getByRole('button',{name:'退出 Q',exact:true}).click();
  const closed=app.waitForEvent('close');await page.getByRole('button',{name:'确认退出',exact:true}).click();await closed;app=null;checks++;
  app=await electron.launch({args:[path.join(__dirname,'smoke-live-main.cjs')],env});
  page=await app.firstWindow();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
  await page.locator('.welcome-scene[data-stage=opening]').waitFor();
  check(await page.locator('.menu-layout').count()===0,'returning launch still starts at cinematic welcome');
  await page.getByRole('button',{name:'跳过开场'}).click();
  const returnButton=page.getByRole('button',{name:`以${longName}身份进入牌厅`,exact:true});
  check((await returnButton.innerText()).includes('一二三四五六…'),'long identity is abbreviated without changing stored name');
  check(await returnButton.evaluate(n=>{const r=n.getBoundingClientRect(),t=n.querySelector('span').getBoundingClientRect();return r.right<=innerWidth&&t.right<r.right;}),'saved-identity button has no overflow');
  await page.screenshot({path:path.join(output,'welcome-returning.png')});
  await returnButton.click();
  await page.locator('.app[data-page=menu]').waitFor();
  check((await page.evaluate(()=>window.desktop.profile.read())).data.nickname===longName,'returning entrance preserves full identity');
  check(errors.length===0,'returning renderer errors: '+errors.join(';'));
  lastState=await captureDiagnostics(page);
  await app.close();app=null;
  await fs.writeFile(path.join(output,'checks.json'),JSON.stringify({checks,errors},null,2)+'\n');
  console.log(`PASS entry ${checks} checks; real first entry, safe preview, cancel/confirm quit and match leave`);
 }catch(e){failure={message:e.message,stack:e.stack};throw e;}finally{
  const state=await (page&&!page.isClosed()?captureDiagnostics(page):Promise.resolve(lastState||{unavailable:'window already closed'})).catch(e=>({unavailable:e.message}));
  await fs.writeFile(path.join(output,'diagnostics.json'),JSON.stringify({input,finishedAt:new Date().toISOString(),checks,errors,failure,state},null,2)+'\n');
  if(failure&&page&&!page.isClosed())await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});
  if(app){await app.evaluate(async()=>{if(global.__testPort)await global.__testPort.close();}).catch(()=>{});await app.close();}await fs.rm(directory,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
