// Local archive smoke, isolated from the user's profile and running match.
const {_electron:electron}=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const content=require('../../docs/results/R04-T01-b/manual-content/content.json');
(async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'deidei-manual-'));
 const output=path.resolve(__dirname,'../../docs/results/R04-T01-b/manual-ui');
 await fs.mkdir(output,{recursive:true});
 const env={...process.env,DEIDEI_TEST_DATA_DIR:directory};delete env.ELECTRON_RUN_AS_NODE;
 let app;const errors=[];let checks=0;
 const check=(condition,message)=>{assert.ok(condition,message);checks++;};
 try{
  app=await electron.launch({args:[path.join(__dirname,'smoke-live-main.cjs')],env});
  const page=await app.firstWindow();page.setDefaultTimeout(10000);
  page.on('pageerror',error=>errors.push(error.message));
  await page.getByRole('button',{name:'进入牌厅',exact:true}).click();
  await page.getByRole('textbox',{name:'昵称',exact:true}).fill('图鉴验收');
  await page.getByRole('button',{name:'确认名字',exact:true}).click();await page.getByRole('button',{name:'进入主菜单',exact:true}).click();
  await page.getByRole('button',{name:'经典规则手册 R',exact:true}).click();
  await page.locator('.archive-screen').waitFor();
  check(await page.locator('.archive-breadcrumb').count()===0,'redundant breadcrumb removed');
  const search=page.getByRole('textbox',{name:'搜索招式'});
  for(const card of content.cards){
   await search.fill(card.doc_id);
   await page.locator(`.archive-card-detail[data-entry="${card.entry_id}"]`).waitFor();
   check(await page.locator('.archive-card-title h2').innerText()===card.name,card.entry_id+' title');
   check((await page.locator('.archive-warning').first().innerText()).includes(card.beginner.watch_out),card.entry_id+' critical risk');
   check(await page.locator('.archive-costs article').count()===card.costs.length,card.entry_id+' cost states');
   await page.getByRole('tab',{name:'精确属性与完整限制',exact:true}).click();
   check(await page.locator('.archive-mode').count()===card.combat_modes.length,card.entry_id+' precision modes');
   await page.getByRole('tab',{name:'先看懂',exact:true}).click();
   await page.getByRole('button',{name:'4 · 这一拍之后',exact:true}).click();
   check((await page.locator('.archive-example').innerText()).includes('本拍淘汰')||(await page.locator('.archive-example').innerText()).includes('双方仍在场'),card.entry_id+' example');
  }
  await search.fill('E07');await page.locator('.archive-card-detail[data-entry="Reflect"]').waitFor();
  check((await page.locator('.archive-example').innerText()).includes('场景 1：bi 遇到反弹'),'positive reflection example');
  await page.evaluate(()=>{
   const example=document.querySelector('.archive-example');
   window.archiveTiming=[];
   const observer=new MutationObserver(records=>{
    for(const record of records){
     if(record.attributeName==='data-beat')window.archiveTiming.push([Number(example.dataset.beat),performance.now()]);
     if(record.attributeName==='data-playing'){
      if(example.dataset.playing==='true'&&!window.archiveTiming.length)window.archiveTiming.push([0,performance.now()]);
      if(example.dataset.playing==='false'&&Number(example.querySelector('[role="progressbar"]').getAttribute('aria-valuenow'))===100){window.archiveTiming.push([4,performance.now()]);observer.disconnect();}
     }
    }
   });
   observer.observe(example,{attributes:true,attributeFilter:['data-beat','data-playing']});
  });
  await page.getByRole('button',{name:'播放场景演示',exact:true}).click();
  await page.waitForTimeout(900);
  await page.getByRole('button',{name:'暂停场景演示',exact:true}).click();
  const pausedProgress=await page.getByRole('progressbar',{name:'场景播放进度'}).getAttribute('aria-valuenow');
  await page.waitForTimeout(350);
  check(await page.getByRole('progressbar',{name:'场景播放进度'}).getAttribute('aria-valuenow')===pausedProgress,'pause freezes the ring');
  check(Number(pausedProgress)>0&&Number(pausedProgress)<25,'ring follows the first step');
  await page.getByRole('button',{name:'播放场景演示',exact:true}).click();
  await page.getByRole('button',{name:'重播场景演示',exact:true}).waitFor({timeout:15000});
  const timing=await page.evaluate(()=>window.archiveTiming);
  check(timing.length===5,'all four reading steps played');
  for(let index=1;index<timing.length;index++)check(timing[index][1]-timing[index-1][1]>=2480,'2.5-second dwell, frame tolerance: step '+index);
  check(timing[4][1]-timing[0][1]>=10000,'full playback takes at least ten seconds');
  check(await page.getByRole('button',{name:'直接看结果',exact:true}).count()===0,'remove the redundant result shortcut');
  const playGeometry=await page.locator('.archive-play-control').evaluate(node=>{
   const control=node.getBoundingClientRect(),header=node.closest('header').getBoundingClientRect();
   return control.right===header.right&&control.top>=header.top&&control.bottom<=header.bottom;
  });
  check(playGeometry,'playback control sits in the top-right header');
  check(await page.locator('.archive-demo-trail[data-kind="return"]').count()===1,'return effect comes from the core ledger');
  check((await page.locator('.archive-example-result').innerText()).includes('左方')&&(await page.locator('.archive-example-result').innerText()).includes('回击'),'reflection result');
  check((await page.locator('.archive-demo-resources').allInnerTexts()).every(text=>text.includes('0 DD')),'reflection spends both costs');
  await page.screenshot({path:path.join(output,'archive-reflection.png')});
  await search.fill('E10');await page.locator('.archive-card-detail[data-entry="Bomb"]').waitFor();
  await page.getByRole('button',{name:'第 2 拍',exact:true}).click();
  check((await page.locator('.archive-demo-resources').first().innerText()).includes('待成熟炸药 1'),'bomb waiting state');
  await page.getByRole('button',{name:'4 · 这一拍之后',exact:true}).click();
  check((await page.locator('.archive-demo-resources').first().innerText()).includes('成熟炸药 1'),'bomb maturity');
  check(await page.locator('.archive-example-context').count()===0,'bomb setup copy is replaced by visual resources');
  await page.locator('.archive-example header').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'archive-playback.png')});
  await page.locator('.archive-relations details summary').click();
  const relationGeometry=await page.locator('.archive-more-relations').evaluate(node=>{
   const group=node.getBoundingClientRect(),buttons=[...node.querySelectorAll('button')].map(button=>button.getBoundingClientRect());
   return buttons.every(button=>Math.abs(button.width-group.width)<1)&&buttons.slice(1).every((button,index)=>button.top-buttons[index].bottom>=7);
  });
  check(relationGeometry,'expanded relation cards have equal full width and spacing');
  await page.locator('.archive-relations details').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'archive-relations.png')});
  await search.fill('E26');await page.locator('.archive-card-detail[data-entry="LiQiang"]').waitFor();
  check(await page.locator('.archive-example-picker>div button').first().innerText()==='场景 1：对手连续出三雷','plain scenario title');
  check(await page.locator('.archive-example-picker>div button').nth(1).innerText()==='场景 2：对手没有上一招记录','second scenario is numbered');
  await page.locator('.archive-example header').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'archive-scenarios.png')});
  await search.fill('E32');await page.locator('.archive-card-detail[data-entry="ZengYi"]').waitFor();
  await page.getByRole('button',{name:'第 2 拍',exact:true}).click();
  await page.getByRole('button',{name:'2 · 同时揭晓',exact:true}).click();
  check((await page.locator('.archive-example').innerText()).includes('系统休整'),'forced recovery rendering');
  await page.getByRole('button',{name:'第 5 拍',exact:true}).click();
  await page.getByRole('button',{name:'4 · 这一拍之后',exact:true}).click();
  check((await page.locator('.archive-demo-resources').first().innerText()).includes('奖励已就绪'),'reward timing');
  await search.fill('E01');await page.locator('.archive-card-detail[data-entry="Charge"]').waitFor();
  const rail=page.locator('.archive-scene-rail');
  check(await rail.locator('button').count()===content.cards[0].beginner.example_ids.length,'all scenes appear in one rail');
  check(await page.locator('.archive-example-picker details').count()===0,'no more-scenes disclosure');
  check(await rail.locator('button').first().getAttribute('aria-pressed')==='true','first scene selected by default');
  await rail.scrollIntoViewIfNeeded();
  const railBox=await rail.boundingBox(),detailScroll=await page.locator('.archive-detail-scroll').evaluate(node=>node.scrollTop);
  await page.mouse.move(railBox.x+railBox.width/2,railBox.y+18);await page.mouse.wheel(0,240);
  await page.waitForFunction(()=>document.querySelector('.archive-scene-rail').scrollLeft>0);
  check(await page.locator('.archive-detail-scroll').evaluate(node=>node.scrollTop)===detailScroll,'scene wheel scrolls sideways without moving guide');
  check(await rail.evaluate(node=>getComputedStyle(node).maskImage.includes('linear-gradient')),'scenes fade at both horizontal edges');
  await rail.locator('button').filter({hasText:'云遇到攒'}).click();
  check((await page.locator('.archive-example').innerText()).includes('云遇到攒'),'expanded example changes the playback');
  await search.fill('不存在的牌');
  check(await page.locator('.archive-no-match').isVisible(),'empty search state');
  check(await page.locator('.archive-card-detail').count()===0,'empty state must not leave a stale card');
  await page.getByRole('button',{name:'显示全部招式'}).click();
  for(const [category,count] of [['攻击',18],['防御',9],['技能',6],['全部',33]]){
   await page.getByRole('navigation',{name:'招式分类'}).getByRole('button',{name:category,exact:true}).click();
   await page.waitForFunction(count=>document.querySelector('[data-count]').dataset.count===String(count),count);
   check(await page.locator('[data-count]').getAttribute('data-count')===String(count),category+' count');
  }
  const stack=page.locator('.archive-stack');
  await stack.focus();await page.keyboard.press('Home');
  await page.waitForFunction(()=>document.querySelector('.archive-stack').scrollTop<1);
  check(await page.getByText('快速查牌',{exact:true}).count()===0,'search heading removed');
  check(await page.locator('.archive-index,.archive-browse-controls').count()===0,'bottom quick controls removed');
  const field=page.locator('.archive-search-field');
  const fieldState=()=>field.evaluate(node=>{const style=getComputedStyle(node);return {border:style.borderColor,shadow:style.boxShadow,background:style.backgroundImage};});
  await page.mouse.move(20,20);await page.waitForTimeout(250);
  const normalInput=await fieldState();
  check(await field.evaluate(node=>getComputedStyle(node).borderRadius)==='0px','search field has square corners');
  check(normalInput.background.includes('), linear-gradient('),'search uses layered gradients');
  await field.screenshot({path:path.join(output,'search-normal.png')});
  await search.hover();await page.waitForTimeout(250);
  const hoverInput=await fieldState();
  check(normalInput.border!==hoverInput.border,'search has a distinct hover state');
  await field.screenshot({path:path.join(output,'search-hover.png')});
  await search.focus();await page.waitForTimeout(250);
  const focusedInput=await fieldState();
  check(focusedInput.border!==hoverInput.border&&focusedInput.shadow!==hoverInput.shadow,'search has a distinct focus state');
  check(await search.evaluate(node=>getComputedStyle(node).caretColor)==='rgb(140, 234, 243)','search caret fits the dark theme');
  await field.screenshot({path:path.join(output,'search-focused.png')});
  await stack.focus();
  const stackBox=await stack.boundingBox();
  await page.mouse.move(stackBox.x+stackBox.width/2,stackBox.y+90);
  const selectedBefore=await page.locator('.archive-card-detail').getAttribute('data-entry');
  await page.mouse.wheel(0,65);
  await page.waitForFunction(()=>document.querySelector('.archive-stack').scrollTop>40);
  const partialScroll=await stack.evaluate(node=>node.scrollTop);
  check(partialScroll>0&&partialScroll<148,'wheel scrolls continuously between card positions');
  check(await page.locator('.archive-card-detail').getAttribute('data-entry')===selectedBefore,'browsing does not replace the selected guide');
  await page.screenshot({path:path.join(output,'archive-stack-scrolling.png')});
  await stack.locator('[data-entry="Bi"]').click();
  await page.locator('.archive-card-detail[data-entry="Bi"]').waitFor();
  await page.waitForFunction(()=>Math.abs(document.querySelector('.archive-stack').scrollTop-148)<1);
  await page.waitForFunction(()=>{const stack=document.querySelector('.archive-stack'),front=stack.querySelector('[data-entry="Bi"]');return Math.abs(parseFloat(front.style.top)-32)<.1;});
  const stackGeometry=await page.evaluate(()=>{
   const stack=document.querySelector('.archive-stack'),top=stack.getBoundingClientRect().top;
   const buttons=[...stack.querySelectorAll('.archive-stack-item')].slice(1,5);
   const rows=buttons.map(button=>{const r=button.getBoundingClientRect(),card=button.querySelector('.archive-stack-card');return {top:r.top-top,bottom:r.bottom-top,width:r.width,height:r.height,filter:getComputedStyle(card).filter};});
   const front=buttons[0],r=front.getBoundingClientRect();
   const hittable=[[r.left+16,r.top+16],[r.right-16,r.bottom-16],[r.left+r.width/2,r.top+r.height/2]].every(([x,y])=>document.elementFromPoint(x,y)?.closest('button')===front);
   const style=getComputedStyle(stack),cardStyle=getComputedStyle(front.querySelector('.archive-stack-card'));
   return {rows,hittable,frontHeight:stack.clientHeight,mask:style.maskImage,maskComposite:style.maskComposite,previousOpacity:getComputedStyle(stack.querySelector('.archive-stack-item')).opacity,corner:cardStyle.borderRadius,background:cardStyle.backgroundImage,shadow:cardStyle.boxShadow,tailOpacity:[...stack.querySelectorAll('.archive-stack-item')].slice(5,7).map(button=>Number(getComputedStyle(button).opacity))};
  });
  check(stackGeometry.previousOpacity==='0','previous card fades away without a leftover border');
  check(stackGeometry.tailOpacity[0]===1&&stackGeometry.tailOpacity[1]===0,'far cards fade out before their render boundary');
  check(stackGeometry.corner==='0px','list cards have square corners');
  check(stackGeometry.background.includes('), linear-gradient('),'selected card uses layered gradients');
  check(stackGeometry.mask.includes('linear-gradient')&&stackGeometry.maskComposite.split(', ').every(value=>value==='intersect'),'scroll boundaries fade vertically and horizontally');
  check(stackGeometry.rows[0].top>=28&&stackGeometry.rows[0].bottom<=stackGeometry.frontHeight-28,'front card stays inside the clear region with shadow room');
  check(stackGeometry.hittable,'the full front card is easy to click');
  check(stackGeometry.rows[0].top>=0&&stackGeometry.rows[0].bottom<=stackGeometry.frontHeight,'front card is fully visible');
  check(stackGeometry.rows.slice(1).every((row,index)=>row.width<stackGeometry.rows[index].width),'deeper cards narrow progressively');
  const overlap=stackGeometry.rows.slice(1).map((row,index)=>(stackGeometry.rows[index].bottom-row.top)/row.height);
  check(overlap.every((amount,index)=>amount>0&&(index===0||amount>overlap[index-1])),'lower cards overlap progressively more');
  check(stackGeometry.rows[0].filter!==stackGeometry.rows[3].filter,'depth increases down the stack');
  await page.mouse.move(20,20);
  await page.screenshot({path:path.join(output,'archive-stack.png')});
  // Sample actual rendered frames, including the gap between native scrolling and React updates.
  await stack.focus();await page.keyboard.press('Home');
  await page.waitForFunction(()=>document.querySelector('.archive-stack').scrollTop<1);
  await page.evaluate(()=>{window.__archiveScrollFrames=[];let count=0;const frame=()=>{const node=document.querySelector('.archive-stack'),r=node.getBoundingClientRect(),visible=[...node.querySelectorAll('.archive-stack-item')].filter(button=>{const b=button.getBoundingClientRect(),style=getComputedStyle(button);return style.visibility!=='hidden'&&Number(style.opacity)>.1&&b.bottom>r.top+28&&b.top<r.bottom-56;}).length;window.__archiveScrollFrames.push({scroll:node.scrollTop,visible});if(++count<90)requestAnimationFrame(frame);};requestAnimationFrame(frame);});
  await page.mouse.move(stackBox.x+stackBox.width/2,stackBox.y+90);
  for(let index=0;index<6;index++)await page.mouse.wheel(0,580);
  await page.waitForFunction(()=>window.__archiveScrollFrames.length===90);
  const scrollFrames=await page.evaluate(()=>window.__archiveScrollFrames);
  check(scrollFrames.some(frame=>frame.scroll>2900),'fast scroll traverses many cards');
  check(scrollFrames.every(frame=>frame.visible>0),'fast scroll has no empty card frames');
  await fs.writeFile(path.join(output,'scroll-after.json'),JSON.stringify({frames:scrollFrames},null,2)+'\n');
  await stack.focus();await page.keyboard.press('End');
  await page.waitForFunction(()=>{const node=document.querySelector('.archive-stack');return Math.abs(node.scrollTop-(node.scrollHeight-node.clientHeight))<1;});
  check(await page.locator('.archive-card-detail').getAttribute('data-entry')===content.cards.at(-1).entry_id,'last card is reachable');
  await page.waitForFunction(()=>parseFloat(document.querySelector('.archive-stack-item[data-selected=true]').style.top)===32);
  await stack.locator('[data-selected=true]').hover();await page.mouse.wheel(0,-65);
  await page.waitForFunction(()=>{const node=document.querySelector('.archive-stack');return node.scrollTop<node.scrollHeight-node.clientHeight-40;});
  check(await page.locator('.archive-card-detail').getAttribute('data-entry')===content.cards.at(-1).entry_id,'scrolling up preserves selection');
  await page.locator('.archive-stack').focus();
  await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');
  await page.locator('.archive-card-detail[data-entry="Def"]').waitFor();checks++;
  await page.getByRole('button',{name:'切换为图标显示',exact:true}).click();
  const grid=page.locator('.archive-icon-grid');
  check(await grid.locator('.archive-icon-tile').count()===33,'icon grid contains all cards');
  check(await grid.evaluate(node=>node.scrollTop)===0,'icon grid opens from its top');
  const tiles=await grid.locator('.archive-icon-tile').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {left:r.left,top:r.top,bottom:r.bottom,width:r.width,height:r.height,radius:getComputedStyle(node).borderRadius,text:node.textContent};}));
  check(tiles.every(tile=>Math.abs(tile.width-tile.height)<1&&tile.radius==='0px'&&tile.text===''),'grid uses square icon-only tiles');
  const firstColumn=tiles.filter(tile=>Math.abs(tile.left-tiles[0].left)<1);
  check(firstColumn.slice(1).every((tile,index)=>tile.top-firstColumn[index].bottom>=9),'icon grid rows keep clear spacing without overlap');
  await grid.locator('[data-entry="BigBi"]').click();await page.locator('.archive-card-detail[data-entry="BigBi"]').waitFor();
  check(await grid.locator('[data-entry="BigBi"]').getAttribute('aria-pressed')==='true','icon click selects its guide');
  await page.getByRole('navigation',{name:'招式分类'}).getByRole('button',{name:'防御',exact:true}).click();
  check(await grid.locator('.archive-icon-tile').count()===9,'icon grid respects category');
  await page.getByRole('navigation',{name:'招式分类'}).getByRole('button',{name:'全部',exact:true}).click();
  await search.fill('E26');await page.locator('.archive-card-detail[data-entry="LiQiang"]').waitFor();
  check(await grid.locator('.archive-icon-tile').count()===1,'icon grid respects search');
  await page.getByRole('button',{name:'清空搜索',exact:true}).click();
  await page.screenshot({path:path.join(output,'archive-icons.png')});
  await page.getByRole('button',{name:'切换为卡牌显示',exact:true}).click();
  await page.waitForFunction(()=>Math.abs(document.querySelector('.archive-stack').scrollTop-25*148)<1);
  check(await page.locator('.archive-card-detail').getAttribute('data-entry')==='LiQiang','mode switch preserves selection');
  await search.fill('E06');await page.locator('.archive-card-detail[data-entry="BigBi"]').waitFor();
  await page.locator('.archive-relations button').filter({hasText:'普通防御'}).click();
  await page.locator('.archive-card-detail[data-entry="Def"]').waitFor();
  await page.getByRole('button',{name:'‹ 回到 大 bi',exact:true}).click();
  await page.locator('.archive-card-detail[data-entry="BigBi"]').waitFor();checks++;
  await page.locator('.archive-rule-links button').first().click();
  check(await page.locator('.archive-rule-section details[open]').count()>0,'rule link opens original clause');
  await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  check(await page.locator('.archive-card-detail').getAttribute('data-entry')==='BigBi','rule return retains card');
  const egg=page.locator('.archive-egg');await egg.scrollIntoViewIfNeeded();
  await page.locator('.archive-card-title').scrollIntoViewIfNeeded();
  check(await egg.locator('p').isHidden(),'egg hidden by default');
  await egg.getByRole('button',{name:'课间便签'}).click();
  check(await egg.locator('p').isVisible(),'egg keyboard/tap reveal');
  const dialogFit=async label=>{
   await page.waitForTimeout(400);
   const fit=await page.locator('.archive-dialog').evaluate(n=>{const r=n.getBoundingClientRect(),body=n.querySelector('.archive-dialog-scroll');return {fits:r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,inner:body.clientHeight>100&&body.scrollWidth<=body.clientWidth,outer:document.scrollingElement.scrollHeight===innerHeight};});
   check(fit.fits&&fit.inner&&fit.outer,label+' independent dialog fits without page overflow');
   await page.screenshot({path:path.join(output,label+'.png')});
  };
  const retained=await page.locator('.archive-detail-scroll').evaluate(n=>n.scrollTop);
  await page.getByRole('button',{name:'先看三张牌',exact:true}).click();
  check(await page.getByRole('dialog',{name:'先看三张牌',exact:true}).isVisible(),'intro opens separate modal');
  await dialogFit('intro-dialog');
  check(await page.locator('.archive-dialog .archive-play').evaluate(n=>getComputedStyle(n).clipPath==='none'&&getComputedStyle(n).borderRadius==='50%'),'dialog keeps round play button');
  for(let index=0;index<content.onboarding.steps.length;index++){
   await page.locator('.archive-guide-steps button').nth(index).click();
   check((await page.locator('.archive-guide').innerText()).includes(content.onboarding.steps[index].copy),'intro step '+index);
  }
  await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  check(await page.locator('.archive-detail-scroll').evaluate(n=>n.scrollTop)===retained,'closing guide keeps dossier scroll');
  check(await page.getByRole('button',{name:'先看三张牌',exact:true}).evaluate(n=>n===document.activeElement),'ESC restores entrance focus');
  await page.getByRole('button',{name:'常见问题',exact:true}).click();
  check(await page.getByRole('dialog',{name:'常见问题',exact:true}).isVisible(),'FAQ opens separate modal');
  await dialogFit('questions-dialog');
  check(await page.locator('.archive-question').count()===10,'question routes');
  await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'完整规则',exact:true}).click();
  check(await page.getByRole('dialog',{name:'完整规则',exact:true}).isVisible(),'rules open separate modal');
  await dialogFit('rules-dialog');
  for(const chapter of content.chapters){await page.locator('.archive-chapters button').filter({hasText:chapter.title}).click();check((await page.locator('.archive-guide').innerText()).includes(chapter.lead),chapter.id+' route');}
  await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'先看三张牌',exact:true}).click();
  await page.locator('.archive-guide-steps button').first().click();
  await page.getByRole('dialog').getByRole('button',{name:'查看 攒／DeiDei',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'hidden'});
  check(await page.locator('.archive-card-detail').getAttribute('data-entry')==='Charge','dialog card link closes and navigates dossier');
  await search.fill('E11');await page.locator('.archive-card-detail[data-entry="Xiao"]').waitFor();
  await page.getByRole('button',{name:'清空搜索',exact:true}).click();
  const tabGeometry=await page.locator('.archive-card-tabs').evaluate(node=>{const r=node.getBoundingClientRect(),buttons=[...node.querySelectorAll('button')].map(button=>button.getBoundingClientRect());return {width:r.width,parentWidth:node.parentElement.getBoundingClientRect().width,buttons:buttons.map(b=>b.width)};});
  check(Math.abs(tabGeometry.width-tabGeometry.parentWidth)<1&&Math.abs(tabGeometry.buttons[0]-tabGeometry.buttons[1])<1,'reading tabs span the full guide width in equal halves');
  await page.getByRole('tab',{name:'先看懂',exact:true}).focus();await page.keyboard.press('ArrowRight');
  check(await page.getByRole('tab',{name:'精确属性与完整限制',exact:true}).getAttribute('aria-selected')==='true','reading tabs support keyboard switching');
  await page.keyboard.press('ArrowLeft');
  const fit=[];
  for(const [width,height] of [[1000,650],[1366,768],[1920,1080]]){
   await page.setViewportSize({width,height});await page.waitForTimeout(850);
   const geometry=await page.evaluate(()=>{
    const rect=selector=>{const r=document.querySelector(selector).getBoundingClientRect();return [r.left,r.top,r.right,r.bottom];};
    return {viewport:[innerWidth,innerHeight],body:[document.documentElement.scrollWidth,document.documentElement.scrollHeight],detail:rect('.archive-dossier'),toggle:rect('.archive-view-toggle'),stack:rect('.archive-stack'),titleSize:parseFloat(getComputedStyle(document.querySelector('.archive-card-title h2')).fontSize),textSize:parseFloat(getComputedStyle(document.querySelector('.archive-card-title p')).fontSize),inputBg:getComputedStyle(document.querySelector('.archive-search input')).backgroundColor,images:[...document.querySelectorAll('.archive-stack img,.archive-card-title img')].every(img=>img.naturalWidth>0)};
   });
   check(geometry.body[0]===width&&geometry.body[1]===height,'viewport fit '+width);
   for(const key of ['detail','toggle','stack'])check(geometry[key][0]>=0&&geometry[key][1]>=0&&geometry[key][2]<=width+1&&geometry[key][3]<=height+1,key+' in viewport '+width);
   check(geometry.titleSize>=26&&geometry.textSize>=15,'readable title and copy '+width);
   check(geometry.images,'icons loaded '+width);
   check(geometry.inputBg!=='rgb(255, 255, 255)'&&geometry.inputBg!=='rgb(244, 241, 230)','dark search '+width);
   fit.push(geometry);await page.screenshot({path:path.join(output,`archive-${width}.png`)});
   await page.getByRole('button',{name:'切换为图标显示',exact:true}).click();
   const gridFit=await page.locator('.archive-icon-grid').evaluate(node=>{const r=node.getBoundingClientRect(),tiles=[...node.querySelectorAll('button')].map(b=>b.getBoundingClientRect()),firstColumn=tiles.filter(b=>Math.abs(b.left-tiles[0].left)<1);return {fits:r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,noOverlap:firstColumn.slice(1).every((b,i)=>b.top-firstColumn[i].bottom>=9)};});
   check(gridFit.fits,'icon grid fits viewport '+width);check(gridFit.noOverlap,'icon grid row spacing '+width);
   await page.screenshot({path:path.join(output,`archive-icons-${width}.png`)});
   await page.getByRole('button',{name:'切换为卡牌显示',exact:true}).click();
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  check(await page.locator('.archive-screen').evaluate(node=>getComputedStyle(node).animationName)==='none','reduced motion');
  check(await page.locator('.archive-stack-item[data-selected=true] .archive-stack-card').evaluate(node=>getComputedStyle(node,'::after').animationName)==='none','reduced motion stops decorative glint');
  await page.locator('.archive-heading .settings-back').click();await page.locator('.menu-layout').waitFor();checks++;
  await page.getByRole('button',{name:'设置 S',exact:true}).click();await page.locator('.settings-layout').waitFor();
  check(await page.getByRole('button',{name:'保存并关闭',exact:true}).isDisabled(),'settings untouched');
  check(errors.length===0,'renderer errors: '+errors.join(';'));
  await fs.writeFile(path.join(output,'checks.json'),JSON.stringify({checks,fit,stackGeometry,searchStates:{normal:normalInput,hover:hoverInput,focus:focusedInput},playbackTiming:timing,scrollFrames,errors},null,2)+'\n');
  console.log(`PASS: ${checks} archive checks; 33 cards, entry/exit, keyboard, examples, relations, rules, intro, empty state, three viewports and reduced motion.`);
 }finally{if(app)await app.close();await fs.rm(directory,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
