import React,{useEffect,useState} from 'react';
import type {Profile,OpponentStatus} from './types';
import {Avatar,BackButton,RuleButton,TurnTimeSelector} from './SharedUI';
import {MoveArt} from './CardArt';
import {modeLabel,type RulesRequest,type RulesSnapshot,type PackManifest} from './rules/types';
import {RulesSummary} from './rules/RulesSummary';

export function SoloPrepare({profile,busy,onBack,onStart,rules,snapshot,manifests,onRules}:{profile:Profile;busy:boolean;onBack:()=>void;onStart:(opponentId:string)=>void;rules:RulesRequest;snapshot:RulesSnapshot|null;manifests:PackManifest[];onRules:()=>void}) {
 const [opponent,setOpponent]=useState('random-legal-v1'),[status,setStatus]=useState<OpponentStatus|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let alive=true,timer:ReturnType<typeof setTimeout>;setStatus(null);setError('');const poll=async()=>{try{const reply=await window.desktop.port.soloStatus();if(!alive)return;if(!reply.ok)throw Error(reply.error);setStatus(reply.data);if(reply.data.state==='preparing')timer=setTimeout(poll,150);}catch(e){if(alive)setError((e as Error).message);}};void window.desktop.port.prepareSolo(opponent).then(reply=>{if(!alive)return;if(!reply.ok){setError(reply.error);return;}setStatus(reply.data);if(reply.data.state==='preparing')timer=setTimeout(poll,150);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;clearTimeout(timer);void window.desktop.port.cancelSoloPrepare().catch(()=>{});};},[opponent,attempt]);
 const legacy=opponent==='legacy-maskable-ppo-v1',name=legacy?'旧版 AI（试验）':'随机合法对手';
 return <main className="prepare-screen"><BackButton className="settings-back prepare-back" disabled={busy} onClick={onBack}>返回主菜单</BackButton><section className="prepare-overview"><header className="prepare-intro"><span>单人训练</span><h1>{name}。</h1><p>对手先固定本拍决定；本场不限时。规则在开局时冻结。</p></header><section className="prepare-self" aria-label="本机玩家"><Avatar id={profile.avatar_id}/><span><small>本机席位</small><strong>{profile.nickname}</strong></span></section><section className="prepare-config" aria-label="练习设置"><section className="prepare-setting"><RuleButton disabled={busy} label={modeLabel(rules)} onClick={onRules}/></section><section className="prepare-setting"><TurnTimeSelector label="每回合时间" value={0} options={[0,5000,10000,20000,30000]} disabledValues={[5000,10000,20000,30000]} onChange={()=>{}}/></section></section>{snapshot&&<RulesSummary snapshot={snapshot} manifests={manifests}/>}</section><section className="difficulty-console" data-level="standard" aria-labelledby="difficulty-title"><header><span>当前对手</span><h2 id="difficulty-title">{name}</h2></header><div className="prepare-signal" data-level="standard"><span aria-hidden="true"/><span aria-hidden="true"/><span aria-hidden="true"/><i aria-hidden="true"/><div className="difficulty-emblem" aria-hidden="true"><MoveArt entryId="Charge"/></div></div><div className="difficulty-readout"><fieldset disabled={busy}><legend>选择训练对手</legend>{[['random-legal-v1','随机合法对手'],['legacy-maskable-ppo-v1','旧版 AI（试验）']].map(([id,label])=><label className="checkbox" key={id}><input type="radio" name="solo-opponent" checked={opponent===id} onChange={()=>setOpponent(id)}/><span>{label}</span></label>)}</fieldset><p role="status">{status?.state==='ready'?'对手已就绪':status?.state==='preparing'?'正在预热，可取消或返回':status?.state==='failed'?'预热失败，可重试或选择随机对手':'等待准备'}{error&&`（${error}）`}</p>{(status?.state==='failed'||error)&&<button onClick={()=>setAttempt(v=>v+1)}>重试预热</button>}<p>{legacy?'原模型仅覆盖31个旧入口；缺配置与曾义特征，失败时如实标随机回退。':'每拍从当前合法入口中随机选择，不代表模型强度。'}</p>{status?.compatibility.missing_features.length? <small>策略局限：{status.compatibility.missing_features.join('、')}</small>:null}</div></section><footer className="prepare-actions"><button className="prepare-start" disabled={busy||!snapshot||status?.state!=='ready'} onClick={()=>onStart(opponent)}><span>{busy?'正在开场':'开始对局'}</span><small>{busy?'LOADING':'ENTER MATCH'}</small></button></footer></main>;
}
