export type Resources = { dd6: string; lightning: string; nx_charge: string; mature_bombs: string; reward_stock: string };
export type Option = { entry_id: string; doc_id: string; available: boolean; reason_code: string | null; required: Resources; spend: Resources; forced: boolean; name: string; ui_group: 'attack'|'defense'|'skill'; cost_text: string; requirement_text: string; detail_rule_ids: string[] };
export type Participant = { player_id: string; nickname: string; avatar_id: string; alive: boolean; resources: Resources & { enhanced_xiao: boolean; cloud_uses: string; tian_uses: string; bomb_placement_count: string }; submission_state: 'thinking'|'submitted'|'out' };
export type PublicRound = { match_id:string; game_id:string; turn_index:string; turn_id:string; actions:Record<string,{entry_id:string;actual_move:string;branch:string|null;is_recovery:boolean;base_move?:string;origin?:string;upgrade?:null|{kind:'lucky_upgrade';from:string;to:string;probability_bps:number};spend?:Resources}>; next_game_id:string; next_turn_index:string };
export type OpponentStatus={requested_id:string|null;active_id:string|null;state:'idle'|'preparing'|'ready'|'active'|'degraded'|'cancelled'|'failed';compatibility:{missing_features:string[]};model_turns:number;fallback_turns:number};
export type DesktopView = {opponent_status?:OpponentStatus;decision_source?:'legacy_model'|'legal_fallback'|'forced_recovery'|'random_legal'|null; rules_snapshot?:import('./rules/types').RulesSnapshot;rule_pack_manifests?:import('./rules/types').PackManifest[]; mode:'solo'|'tutorial'|'preview'|'multiplayer'; self_role:'player'|'spectator'; self_participation:'active'|'eliminated'|'spectating'|'departing'; public_round:PublicRound|null; tutorial?: {stage:'guided'|'challenge'|'complete';step:number;target_entry_id:string|null;won:boolean;ended:boolean}; source: 'fixture'|'live'|'online'; view_id: string; match_id: string; game_index:string; game_id: string; turn_index: string; phase: 'selecting'|'submitting'|'revealed'|'result'|'error'; participants: Participant[]; self_id: string|null; options: Option[]; selected_entry_id: string|null; submitted: boolean; timer: { mode: 'untimed'|'preview'|'reveal'; remaining_ms: number|null; total_ms: number|null }; summary: string[]; outcome: { winner_id: string|null; reason: string }|null };
export type { GraphicsPreset, GraphicsSettings } from './graphics.cjs';
export type CardStyle = 'illustrated'|'classic';
export type Settings = { music: number; effects: number; fullscreen: boolean; graphics: import('./graphics.cjs').GraphicsSettings; cardStyle: CardStyle };
export type Profile = { profile_version: 3; local_id: string; nickname: string; avatar_id: string; settings: Settings };
export type ProfileInput = Pick<Profile, 'nickname'|'avatar_id'>;
export type Reply<T> = { ok: true; data: T; warnings?:string[] }|{ ok: false; error: string };
export type Manual = { entries: (Option & { description: string })[]; sections: { id: string; text: string }[] };
export type Scene = 'initial'|'midgame'|'spectator'|'eliminated'|'restart'|'winner'|'defeat'|'draw'|'invalid';
export type Bridge = {
  privacy:import('./privacy/types').PrivacyBridge;updates:import('./updates/types').UpdateBridge;hardware:import('./hardware/types').HardwareBridge;
  lifecycle:{reportContext(p:{page:string;experienceDirty:boolean;ruleEditing:boolean;modal:boolean;transitioning:boolean}):Promise<Reply<null>>;onPrepareRestart(listener:(request:{nonce:string;generation:number})=>void):()=>void;replyRestart(p:{nonce:string;generation:number;ready:boolean}):Promise<Reply<null>>};
  rules:{read():Promise<Reply<import('./rules/types').RulesLibrary>>;compile(request:import('./rules/types').RulesRequest):Promise<Reply<{rules_snapshot:import('./rules/types').RulesSnapshot;rule_pack_manifests:import('./rules/types').PackManifest[]}>>;importPack():Promise<Reply<import('./rules/types').RulesLibrary>>;deletePack(ref:import('./rules/types').PackRef):Promise<Reply<import('./rules/types').RulesLibrary>>;savePreset(name:string,request:import('./rules/types').RulesRequest):Promise<Reply<import('./rules/types').RulesLibrary>>;deletePreset(id:string):Promise<Reply<import('./rules/types').RulesLibrary>>};
  online: import('./online/types').OnlineBridge;
  profile: { read(): Promise<Reply<Profile|null>>; create(p: ProfileInput): Promise<Reply<Profile>>; update(p: ProfileInput): Promise<Reply<Profile>>; recover(p: ProfileInput & { confirmed: true }): Promise<Reply<Profile>> };
  settings: {windowState():Promise<Reply<{requested:boolean|null;actual:boolean;pending:boolean}>>;onWindowChange(listener:(state:{requested:boolean|null;actual:boolean;pending:boolean})=>void):()=>void; apply(p: ProfileInput & { settings: Settings;recommendationToken?:string }): Promise<Reply<Profile>> };
  port: { prepareSolo(opponent_id:string):Promise<Reply<OpponentStatus>>;soloStatus():Promise<Reply<OpponentStatus>>;cancelSoloPrepare():Promise<Reply<OpponentStatus>>;startSolo(id: string,request?:import('./rules/types').RulesRequest,opponent_id?:string): Promise<Reply<DesktopView>>; startTutorial(id: string): Promise<Reply<DesktopView>>; tutorialNext(id: string): Promise<Reply<DesktopView>>; submit(id: string, entry: string): Promise<Reply<DesktopView>>; getView(): Promise<Reply<DesktopView>>; leave(): Promise<Reply<DesktopView>> };
  preview(scene: Scene): Promise<Reply<DesktopView>>;
  manual(): Promise<Reply<Manual>>;
  quit(): Promise<Reply<null>>;
};
declare global { interface Window { desktop: Bridge } }
