import type { Option, Reply } from '../types';
export type Policy = {turn_ms:number;early_reveal:boolean;spectator_cap:number;host_disconnect_grace_ms:number;reveal_ms:number;min_select_ms:number};
export type Role = 'player'|'spectator';
export type Member = {player_id:string;nickname:string;avatar_id:string;seat:number|null;role:Role;connected:boolean;ready:boolean;participation:'lobby'|'active'|'eliminated'|'departing'|'spectating';submission_state:'none'|'thinking'|'submitted'|'forced'|'out';absence_count:number};
export type CorePlayer = {dd6:string;lightning:string;nx_charge:string;mature_bombs:string;bomb_placement_count:string;cloud_uses:string;tian_uses:string;enhanced_xiao:boolean;zhang_used:boolean;liq_used:boolean;last_actual_move:string|null;latest_copyable_move:string|null;zeng_state:string;reward_due_turn:string|null;pending_bombs:{game_id:string;placed_turn:string;mature_at_turn_end:string}[]};
export type CoreState = {match_id:string;game_id:string;game_index:string;turn_index:string;roster:string[];active_ids:string[];players:Record<string,CorePlayer>};
export type Transition = {kind:string;from_game_id:string;to_game_id:string;winner_id:string|null};
export type TurnResult = {turn_id:string;core_resolution:{ledger:{actions:Record<string,{entry_id:string;actual_move:string;branch:string|null;origin:string;condition:string|null;is_recovery:boolean;spend:Option['spend']}>;events:{actor_id:string|null;target_id:string|null;kind:string;resource:string|null;resource_delta:string|null;result:string;reason_code:string|null}[];eliminated_ids:string[];post_turn_players:Record<string,CorePlayer>}};room_forfeits:{player_id:string;reason:string}[];effective_transition:Transition;effective_state:CoreState;action_sources:Record<string,string>};
export type RoomSnapshot = {v:1;type:'snapshot';room_id:string;seq:string;server_time_ms:number;view:{source:'online';room_code:string;host_id:string;phase:'lobby'|'selecting'|'revealing'|'result'|'closed';has_password:boolean;policy:Policy;policy_revision:string;current_turn_ms:number|null;host_recovery:null|{kind:'rounds';missing_count:number;close_at_count:4}|{kind:'grace';deadline_at_ms:number;remaining_ms:number};pending_close:null|{reason:'HOST_LEFT';after:'current_turn'|'current_reveal';turn_id:string};members:Member[];self:{player_id:string;role:Role;seat:number|null;options:Pick<Option,'entry_id'|'doc_id'|'available'|'reason_code'|'required'|'spend'|'forced'>[];accepted_entry_id:string|null};match:null|{match_id:string;mode_at_start:string;turn_id:string;public_state:CoreState;roster_profiles:Pick<Member,'player_id'|'nickname'|'avatar_id'|'seat'>[];last_turn:TurnResult|null;effective_outcome:null|{kind:string;winner_id:string|null;reason:string}};timer:{kind:string;remaining_ms:number|null;deadline_at_ms:number|null};pause:null;close_reason:string|null}};
export type MembershipEnd = {v:1;type:'membership.ended';event_id:string;room_id:string;player_id:string;seq:string;server_time_ms:number;reason:'three_absences'|'disconnect_grace_expired';room_code:string|null};
export type OnlineState = {source:'online'|'fixture';status:'idle'|'connecting'|'connected'|'reconnecting'|'unavailable';hello:null|{policy_defaults:Policy;capabilities:{max_players:number;allowed_turn_ms:number[];spectator_max:number}};membership_end:MembershipEnd|null;host_remaining_ms:number|null;snapshot:RoomSnapshot|null;pending:boolean;error:null|{code:string;field:string|null;retryable:boolean};confirmed:null|{room_id:string;match_id:string;turn_id:string;entry_id:string};remaining_ms:number|null;revision:number};
export type OnlineBridge = {
 openLobby():Promise<Reply<OnlineState>>;
 create(p:{password:string|null;options:Pick<Policy,'turn_ms'|'early_reveal'|'spectator_cap'>}):Promise<Reply<OnlineState>>;
 join(p:{room_code:string;password:string|null;role:Role}):Promise<Reply<OnlineState>>;
 ready(p:{room_id:string;ready:boolean}):Promise<Reply<OnlineState>>;
 start(p:{room_id:string}):Promise<Reply<OnlineState>>;
 setTurnLimit(p:{room_id:string;turn_ms:number;expected_policy_revision:string}):Promise<Reply<OnlineState>>;
 changeRole(p:{room_id:string;role:Role}):Promise<Reply<OnlineState>>;
 submit(p:{room_id:string;match_id:string;turn_id:string;entry_id:string}):Promise<Reply<OnlineState>>;
 returnLobby(p:{room_id:string}):Promise<Reply<OnlineState>>;
 leave():Promise<Reply<OnlineState>>;
 read():Promise<Reply<OnlineState>>;
 onChange(listener:(state:OnlineState)=>void):()=>void;
};
